<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_experimental.proto

namespace Ydb\Experimental\ExecuteStreamQueryRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>Ydb.Experimental.ExecuteStreamQueryRequest.ProfileMode</code>
 */
class ProfileMode
{
    /**
     * Generated from protobuf enum <code>PROFILE_MODE_UNSPECIFIED = 0;</code>
     */
    const PROFILE_MODE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>NONE = 1;</code>
     */
    const NONE = 1;
    /**
     * Generated from protobuf enum <code>BASIC = 2;</code>
     */
    const BASIC = 2;
    /**
     * Generated from protobuf enum <code>FULL = 3;</code>
     */
    const FULL = 3;

    private static $valueToName = [
        self::PROFILE_MODE_UNSPECIFIED => 'PROFILE_MODE_UNSPECIFIED',
        self::NONE => 'NONE',
        self::BASIC => 'BASIC',
        self::FULL => 'FULL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ProfileMode::class, \Ydb\Experimental\ExecuteStreamQueryRequest_ProfileMode::class);

