<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_scheme.proto

namespace Ydb\Scheme;

if (false) {
    /**
     * This class is deprecated. Use Ydb\Scheme\Entry\Type instead.
     * @deprecated
     */
    class Entry_Type {}
}
class_exists(Entry\Type::class);
@trigger_error('Ydb\Scheme\Entry_Type is deprecated and will be removed in the next major release. Use Ydb\Scheme\Entry\Type instead', E_USER_DEPRECATED);

