<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_scheme.proto

namespace Ydb\Scheme;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Scheme.Entry</code>
 */
class Entry extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of scheme entry (dir2 of /dir1/dir2)
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * SID (Security ID) of user or group
     *
     * Generated from protobuf field <code>string owner = 2;</code>
     */
    protected $owner = '';
    /**
     * Generated from protobuf field <code>.Ydb.Scheme.Entry.Type type = 5;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>repeated .Ydb.Scheme.Permissions effective_permissions = 6;</code>
     */
    private $effective_permissions;
    /**
     * Generated from protobuf field <code>repeated .Ydb.Scheme.Permissions permissions = 7;</code>
     */
    private $permissions;
    /**
     * Size of entry in bytes. Currently filled for:
     * - TABLE;
     * - DATABASE.
     * Empty (zero) in other cases.
     *
     * Generated from protobuf field <code>uint64 size_bytes = 8;</code>
     */
    protected $size_bytes = 0;
    /**
     * Virtual timestamp when the object was created
     *
     * Generated from protobuf field <code>.Ydb.VirtualTimestamp created_at = 9;</code>
     */
    protected $created_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Name of scheme entry (dir2 of /dir1/dir2)
     *     @type string $owner
     *           SID (Security ID) of user or group
     *     @type int $type
     *     @type array<\Ydb\Scheme\Permissions>|\Google\Protobuf\Internal\RepeatedField $effective_permissions
     *     @type array<\Ydb\Scheme\Permissions>|\Google\Protobuf\Internal\RepeatedField $permissions
     *     @type int|string $size_bytes
     *           Size of entry in bytes. Currently filled for:
     *           - TABLE;
     *           - DATABASE.
     *           Empty (zero) in other cases.
     *     @type \Ydb\VirtualTimestamp $created_at
     *           Virtual timestamp when the object was created
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbScheme::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of scheme entry (dir2 of /dir1/dir2)
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name of scheme entry (dir2 of /dir1/dir2)
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * SID (Security ID) of user or group
     *
     * Generated from protobuf field <code>string owner = 2;</code>
     * @return string
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * SID (Security ID) of user or group
     *
     * Generated from protobuf field <code>string owner = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOwner($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Scheme.Entry.Type type = 5;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Scheme.Entry.Type type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Ydb\Scheme\Entry\Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.Scheme.Permissions effective_permissions = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEffectivePermissions()
    {
        return $this->effective_permissions;
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.Scheme.Permissions effective_permissions = 6;</code>
     * @param array<\Ydb\Scheme\Permissions>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEffectivePermissions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ydb\Scheme\Permissions::class);
        $this->effective_permissions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.Scheme.Permissions permissions = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPermissions()
    {
        return $this->permissions;
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.Scheme.Permissions permissions = 7;</code>
     * @param array<\Ydb\Scheme\Permissions>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPermissions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ydb\Scheme\Permissions::class);
        $this->permissions = $arr;

        return $this;
    }

    /**
     * Size of entry in bytes. Currently filled for:
     * - TABLE;
     * - DATABASE.
     * Empty (zero) in other cases.
     *
     * Generated from protobuf field <code>uint64 size_bytes = 8;</code>
     * @return int|string
     */
    public function getSizeBytes()
    {
        return $this->size_bytes;
    }

    /**
     * Size of entry in bytes. Currently filled for:
     * - TABLE;
     * - DATABASE.
     * Empty (zero) in other cases.
     *
     * Generated from protobuf field <code>uint64 size_bytes = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSizeBytes($var)
    {
        GPBUtil::checkUint64($var);
        $this->size_bytes = $var;

        return $this;
    }

    /**
     * Virtual timestamp when the object was created
     *
     * Generated from protobuf field <code>.Ydb.VirtualTimestamp created_at = 9;</code>
     * @return \Ydb\VirtualTimestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Virtual timestamp when the object was created
     *
     * Generated from protobuf field <code>.Ydb.VirtualTimestamp created_at = 9;</code>
     * @param \Ydb\VirtualTimestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Ydb\VirtualTimestamp::class);
        $this->created_at = $var;

        return $this;
    }

}

