<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_scheme.proto

namespace Ydb\Scheme;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Modify permissions of given object
 *
 * Generated from protobuf message <code>Ydb.Scheme.ModifyPermissionsRequest</code>
 */
class ModifyPermissionsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     */
    protected $operation_params = null;
    /**
     * Generated from protobuf field <code>string path = 2;</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>repeated .Ydb.Scheme.PermissionsAction actions = 3;</code>
     */
    private $actions;
    /**
     * Clear all permissions on the object for all subjects
     *
     * Generated from protobuf field <code>bool clear_permissions = 4;</code>
     */
    protected $clear_permissions = false;
    protected $inheritance;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ydb\Operations\OperationParams $operation_params
     *     @type string $path
     *     @type array<\Ydb\Scheme\PermissionsAction>|\Google\Protobuf\Internal\RepeatedField $actions
     *     @type bool $clear_permissions
     *           Clear all permissions on the object for all subjects
     *     @type bool $interrupt_inheritance
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbScheme::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     * @return \Ydb\Operations\OperationParams|null
     */
    public function getOperationParams()
    {
        return $this->operation_params;
    }

    public function hasOperationParams()
    {
        return isset($this->operation_params);
    }

    public function clearOperationParams()
    {
        unset($this->operation_params);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     * @param \Ydb\Operations\OperationParams $var
     * @return $this
     */
    public function setOperationParams($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Operations\OperationParams::class);
        $this->operation_params = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.Scheme.PermissionsAction actions = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActions()
    {
        return $this->actions;
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.Scheme.PermissionsAction actions = 3;</code>
     * @param array<\Ydb\Scheme\PermissionsAction>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ydb\Scheme\PermissionsAction::class);
        $this->actions = $arr;

        return $this;
    }

    /**
     * Clear all permissions on the object for all subjects
     *
     * Generated from protobuf field <code>bool clear_permissions = 4;</code>
     * @return bool
     */
    public function getClearPermissions()
    {
        return $this->clear_permissions;
    }

    /**
     * Clear all permissions on the object for all subjects
     *
     * Generated from protobuf field <code>bool clear_permissions = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setClearPermissions($var)
    {
        GPBUtil::checkBool($var);
        $this->clear_permissions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool interrupt_inheritance = 5;</code>
     * @return bool
     */
    public function getInterruptInheritance()
    {
        return $this->readOneof(5);
    }

    public function hasInterruptInheritance()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>bool interrupt_inheritance = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setInterruptInheritance($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getInheritance()
    {
        return $this->whichOneof("inheritance");
    }

}

