<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_query.proto

namespace Ydb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Query.BeginTransactionResponse</code>
 */
class BeginTransactionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Ydb.StatusIds.StatusCode status = 1;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>repeated .Ydb.Issue.IssueMessage issues = 2;</code>
     */
    private $issues;
    /**
     * Generated from protobuf field <code>.Ydb.Query.TransactionMeta tx_meta = 3;</code>
     */
    protected $tx_meta = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *     @type array<\Ydb\Issue\IssueMessage>|\Google\Protobuf\Internal\RepeatedField $issues
     *     @type \Ydb\Query\TransactionMeta $tx_meta
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Ydb.StatusIds.StatusCode status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.Ydb.StatusIds.StatusCode status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Ydb\StatusIds\StatusCode::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.Issue.IssueMessage issues = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIssues()
    {
        return $this->issues;
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.Issue.IssueMessage issues = 2;</code>
     * @param array<\Ydb\Issue\IssueMessage>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIssues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ydb\Issue\IssueMessage::class);
        $this->issues = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Query.TransactionMeta tx_meta = 3;</code>
     * @return \Ydb\Query\TransactionMeta|null
     */
    public function getTxMeta()
    {
        return $this->tx_meta;
    }

    public function hasTxMeta()
    {
        return isset($this->tx_meta);
    }

    public function clearTxMeta()
    {
        unset($this->tx_meta);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Query.TransactionMeta tx_meta = 3;</code>
     * @param \Ydb\Query\TransactionMeta $var
     * @return $this
     */
    public function setTxMeta($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Query\TransactionMeta::class);
        $this->tx_meta = $var;

        return $this;
    }

}

