<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_query.proto

namespace Ydb\Query;

use UnexpectedValueException;

/**
 * Protobuf type <code>Ydb.Query.ExecStatus</code>
 */
class ExecStatus
{
    /**
     * Generated from protobuf enum <code>EXEC_STATUS_UNSPECIFIED = 0;</code>
     */
    const EXEC_STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>EXEC_STATUS_STARTING = 10;</code>
     */
    const EXEC_STATUS_STARTING = 10;
    /**
     * Generated from protobuf enum <code>EXEC_STATUS_ABORTED = 20;</code>
     */
    const EXEC_STATUS_ABORTED = 20;
    /**
     * Generated from protobuf enum <code>EXEC_STATUS_CANCELLED = 30;</code>
     */
    const EXEC_STATUS_CANCELLED = 30;
    /**
     * Generated from protobuf enum <code>EXEC_STATUS_COMPLETED = 40;</code>
     */
    const EXEC_STATUS_COMPLETED = 40;
    /**
     * Generated from protobuf enum <code>EXEC_STATUS_FAILED = 50;</code>
     */
    const EXEC_STATUS_FAILED = 50;

    private static $valueToName = [
        self::EXEC_STATUS_UNSPECIFIED => 'EXEC_STATUS_UNSPECIFIED',
        self::EXEC_STATUS_STARTING => 'EXEC_STATUS_STARTING',
        self::EXEC_STATUS_ABORTED => 'EXEC_STATUS_ABORTED',
        self::EXEC_STATUS_CANCELLED => 'EXEC_STATUS_CANCELLED',
        self::EXEC_STATUS_COMPLETED => 'EXEC_STATUS_COMPLETED',
        self::EXEC_STATUS_FAILED => 'EXEC_STATUS_FAILED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

