<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_query.proto

namespace Ydb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Query.ExecuteScriptMetadata</code>
 */
class ExecuteScriptMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string execution_id = 1 [(.Ydb.length) = {</code>
     */
    protected $execution_id = '';
    /**
     * Generated from protobuf field <code>.Ydb.Query.ExecStatus exec_status = 2;</code>
     */
    protected $exec_status = 0;
    /**
     * Generated from protobuf field <code>.Ydb.Query.QueryContent script_content = 3;</code>
     */
    protected $script_content = null;
    /**
     * Generated from protobuf field <code>repeated .Ydb.Query.ResultSetMeta result_sets_meta = 4;</code>
     */
    private $result_sets_meta;
    /**
     * Generated from protobuf field <code>.Ydb.Query.ExecMode exec_mode = 5;</code>
     */
    protected $exec_mode = 0;
    /**
     * Execution statistics
     *
     * Generated from protobuf field <code>.Ydb.TableStats.QueryStats exec_stats = 6;</code>
     */
    protected $exec_stats = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $execution_id
     *     @type int $exec_status
     *     @type \Ydb\Query\QueryContent $script_content
     *     @type array<\Ydb\Query\ResultSetMeta>|\Google\Protobuf\Internal\RepeatedField $result_sets_meta
     *     @type int $exec_mode
     *     @type \Ydb\TableStats\QueryStats $exec_stats
     *           Execution statistics
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string execution_id = 1 [(.Ydb.length) = {</code>
     * @return string
     */
    public function getExecutionId()
    {
        return $this->execution_id;
    }

    /**
     * Generated from protobuf field <code>string execution_id = 1 [(.Ydb.length) = {</code>
     * @param string $var
     * @return $this
     */
    public function setExecutionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->execution_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Query.ExecStatus exec_status = 2;</code>
     * @return int
     */
    public function getExecStatus()
    {
        return $this->exec_status;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Query.ExecStatus exec_status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setExecStatus($var)
    {
        GPBUtil::checkEnum($var, \Ydb\Query\ExecStatus::class);
        $this->exec_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Query.QueryContent script_content = 3;</code>
     * @return \Ydb\Query\QueryContent|null
     */
    public function getScriptContent()
    {
        return $this->script_content;
    }

    public function hasScriptContent()
    {
        return isset($this->script_content);
    }

    public function clearScriptContent()
    {
        unset($this->script_content);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Query.QueryContent script_content = 3;</code>
     * @param \Ydb\Query\QueryContent $var
     * @return $this
     */
    public function setScriptContent($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Query\QueryContent::class);
        $this->script_content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.Query.ResultSetMeta result_sets_meta = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResultSetsMeta()
    {
        return $this->result_sets_meta;
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.Query.ResultSetMeta result_sets_meta = 4;</code>
     * @param array<\Ydb\Query\ResultSetMeta>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResultSetsMeta($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ydb\Query\ResultSetMeta::class);
        $this->result_sets_meta = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Query.ExecMode exec_mode = 5;</code>
     * @return int
     */
    public function getExecMode()
    {
        return $this->exec_mode;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Query.ExecMode exec_mode = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setExecMode($var)
    {
        GPBUtil::checkEnum($var, \Ydb\Query\ExecMode::class);
        $this->exec_mode = $var;

        return $this;
    }

    /**
     * Execution statistics
     *
     * Generated from protobuf field <code>.Ydb.TableStats.QueryStats exec_stats = 6;</code>
     * @return \Ydb\TableStats\QueryStats|null
     */
    public function getExecStats()
    {
        return $this->exec_stats;
    }

    public function hasExecStats()
    {
        return isset($this->exec_stats);
    }

    public function clearExecStats()
    {
        unset($this->exec_stats);
    }

    /**
     * Execution statistics
     *
     * Generated from protobuf field <code>.Ydb.TableStats.QueryStats exec_stats = 6;</code>
     * @param \Ydb\TableStats\QueryStats $var
     * @return $this
     */
    public function setExecStats($var)
    {
        GPBUtil::checkMessage($var, \Ydb\TableStats\QueryStats::class);
        $this->exec_stats = $var;

        return $this;
    }

}

