<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_query.proto

namespace Ydb\Query;

use UnexpectedValueException;

/**
 * Protobuf type <code>Ydb.Query.SchemaInclusionMode</code>
 */
class SchemaInclusionMode
{
    /**
     * Unspecified mode, corresponds to SCHEMA_INCLUSION_MODE_ALWAYS.
     *
     * Generated from protobuf enum <code>SCHEMA_INCLUSION_MODE_UNSPECIFIED = 0;</code>
     */
    const SCHEMA_INCLUSION_MODE_UNSPECIFIED = 0;
    /**
     * Always include schema in every Ydb.ResultSet in the response stream.
     *
     * Generated from protobuf enum <code>SCHEMA_INCLUSION_MODE_ALWAYS = 1;</code>
     */
    const SCHEMA_INCLUSION_MODE_ALWAYS = 1;
    /**
     * Include schema only in the first Ydb.ResultSet per result_set_index of the response stream.
     *
     * Generated from protobuf enum <code>SCHEMA_INCLUSION_MODE_FIRST_ONLY = 2;</code>
     */
    const SCHEMA_INCLUSION_MODE_FIRST_ONLY = 2;

    private static $valueToName = [
        self::SCHEMA_INCLUSION_MODE_UNSPECIFIED => 'SCHEMA_INCLUSION_MODE_UNSPECIFIED',
        self::SCHEMA_INCLUSION_MODE_ALWAYS => 'SCHEMA_INCLUSION_MODE_ALWAYS',
        self::SCHEMA_INCLUSION_MODE_FIRST_ONLY => 'SCHEMA_INCLUSION_MODE_FIRST_ONLY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

