<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_topic.proto

namespace Ydb\Topic\AddOffsetsToTransactionRequest\TopicOffsets;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Topic.AddOffsetsToTransactionRequest.TopicOffsets.PartitionOffsets</code>
 */
class PartitionOffsets extends \Google\Protobuf\Internal\Message
{
    /**
     * Partition identifier.
     *
     * Generated from protobuf field <code>int64 partition_id = 1;</code>
     */
    protected $partition_id = 0;
    /**
     * List of offset ranges.
     *
     * Generated from protobuf field <code>repeated .Ydb.Topic.OffsetsRange partition_offsets = 2;</code>
     */
    private $partition_offsets;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $partition_id
     *           Partition identifier.
     *     @type array<\Ydb\Topic\OffsetsRange>|\Google\Protobuf\Internal\RepeatedField $partition_offsets
     *           List of offset ranges.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTopic::initOnce();
        parent::__construct($data);
    }

    /**
     * Partition identifier.
     *
     * Generated from protobuf field <code>int64 partition_id = 1;</code>
     * @return int|string
     */
    public function getPartitionId()
    {
        return $this->partition_id;
    }

    /**
     * Partition identifier.
     *
     * Generated from protobuf field <code>int64 partition_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPartitionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->partition_id = $var;

        return $this;
    }

    /**
     * List of offset ranges.
     *
     * Generated from protobuf field <code>repeated .Ydb.Topic.OffsetsRange partition_offsets = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPartitionOffsets()
    {
        return $this->partition_offsets;
    }

    /**
     * List of offset ranges.
     *
     * Generated from protobuf field <code>repeated .Ydb.Topic.OffsetsRange partition_offsets = 2;</code>
     * @param array<\Ydb\Topic\OffsetsRange>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPartitionOffsets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ydb\Topic\OffsetsRange::class);
        $this->partition_offsets = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PartitionOffsets::class, \Ydb\Topic\AddOffsetsToTransactionRequest_TopicOffsets_PartitionOffsets::class);

