<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_cms.proto

namespace Ydb\Cms;

if (false) {
    /**
     * This class is deprecated. Use Ydb\Cms\GetDatabaseStatusResult\State instead.
     * @deprecated
     */
    class GetDatabaseStatusResult_State {}
}
class_exists(GetDatabaseStatusResult\State::class);
@trigger_error('Ydb\Cms\GetDatabaseStatusResult_State is deprecated and will be removed in the next major release. Use Ydb\Cms\GetDatabaseStatusResult\State instead', E_USER_DEPRECATED);

