<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_persqueue_v1.proto

namespace Ydb\PersQueue\V1\StreamingReadClientMessageNew;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Add topic to current read session
 *
 * Generated from protobuf message <code>Ydb.PersQueue.V1.StreamingReadClientMessageNew.AddTopicRequest</code>
 */
class AddTopicRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.TopicReadSettings topic_read_settings = 1;</code>
     */
    protected $topic_read_settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ydb\PersQueue\V1\StreamingReadClientMessageNew\TopicReadSettings $topic_read_settings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kikimr\PBPublic\Api\Protos\YdbPersqueueV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.TopicReadSettings topic_read_settings = 1;</code>
     * @return \Ydb\PersQueue\V1\StreamingReadClientMessageNew\TopicReadSettings
     */
    public function getTopicReadSettings()
    {
        return isset($this->topic_read_settings) ? $this->topic_read_settings : null;
    }

    public function hasTopicReadSettings()
    {
        return isset($this->topic_read_settings);
    }

    public function clearTopicReadSettings()
    {
        unset($this->topic_read_settings);
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.TopicReadSettings topic_read_settings = 1;</code>
     * @param \Ydb\PersQueue\V1\StreamingReadClientMessageNew\TopicReadSettings $var
     * @return $this
     */
    public function setTopicReadSettings($var)
    {
        GPBUtil::checkMessage($var, \Ydb\PersQueue\V1\StreamingReadClientMessageNew\TopicReadSettings::class);
        $this->topic_read_settings = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AddTopicRequest::class, \Ydb\PersQueue\V1\StreamingReadClientMessageNew_AddTopicRequest::class);

