<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ydb_federation_discovery_v1.proto

namespace GPBMetadata;

class YdbFederationDiscoveryV1
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Protos\YdbFederationDiscovery::initOnce();
        $pool->internalAddGeneratedFile(
            '
ã
!ydb_federation_discovery_v1.protoYdb.FederationDiscovery.V12«
FederationDiscoveryServiceŒ
ListFederationDatabases7.Ydb.FederationDiscovery.ListFederationDatabasesRequest8.Ydb.FederationDiscovery.ListFederationDatabasesResponseBl
&tech.ydb.proto.federation.discovery.v1ZBgithub.com/ydb-platform/ydb-go-genproto/Ydb_FederationDiscovery_V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

