<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_persqueue_cluster_discovery.proto

namespace Ydb\PersQueue\ClusterDiscovery;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.PersQueue.ClusterDiscovery.WriteSessionParams</code>
 */
class WriteSessionParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Path to the topic to write to.
     *
     * Generated from protobuf field <code>string topic = 1;</code>
     */
    protected $topic = '';
    /**
     * Message group identifier.
     *
     * Generated from protobuf field <code>bytes source_id = 2;</code>
     */
    protected $source_id = '';
    /**
     * Partition group to write to. 0 by default.
     *
     * Generated from protobuf field <code>uint32 partition_group = 3;</code>
     */
    protected $partition_group = 0;
    /**
     * Force the specified cluster via its name. Leave it empty by default.
     *
     * Generated from protobuf field <code>string preferred_cluster_name = 4;</code>
     */
    protected $preferred_cluster_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $topic
     *           Path to the topic to write to.
     *     @type string $source_id
     *           Message group identifier.
     *     @type int $partition_group
     *           Partition group to write to. 0 by default.
     *     @type string $preferred_cluster_name
     *           Force the specified cluster via its name. Leave it empty by default.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kikimr\PBPublic\Api\Protos\YdbPersqueueClusterDiscovery::initOnce();
        parent::__construct($data);
    }

    /**
     * Path to the topic to write to.
     *
     * Generated from protobuf field <code>string topic = 1;</code>
     * @return string
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * Path to the topic to write to.
     *
     * Generated from protobuf field <code>string topic = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic = $var;

        return $this;
    }

    /**
     * Message group identifier.
     *
     * Generated from protobuf field <code>bytes source_id = 2;</code>
     * @return string
     */
    public function getSourceId()
    {
        return $this->source_id;
    }

    /**
     * Message group identifier.
     *
     * Generated from protobuf field <code>bytes source_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceId($var)
    {
        GPBUtil::checkString($var, False);
        $this->source_id = $var;

        return $this;
    }

    /**
     * Partition group to write to. 0 by default.
     *
     * Generated from protobuf field <code>uint32 partition_group = 3;</code>
     * @return int
     */
    public function getPartitionGroup()
    {
        return $this->partition_group;
    }

    /**
     * Partition group to write to. 0 by default.
     *
     * Generated from protobuf field <code>uint32 partition_group = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPartitionGroup($var)
    {
        GPBUtil::checkUint32($var);
        $this->partition_group = $var;

        return $this;
    }

    /**
     * Force the specified cluster via its name. Leave it empty by default.
     *
     * Generated from protobuf field <code>string preferred_cluster_name = 4;</code>
     * @return string
     */
    public function getPreferredClusterName()
    {
        return $this->preferred_cluster_name;
    }

    /**
     * Force the specified cluster via its name. Leave it empty by default.
     *
     * Generated from protobuf field <code>string preferred_cluster_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPreferredClusterName($var)
    {
        GPBUtil::checkString($var, True);
        $this->preferred_cluster_name = $var;

        return $this;
    }

}

