<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_clickhouse_internal.proto

namespace GPBMetadata\Kikimr\PBPublic\Api\Protos;

class YdbClickhouseInternal
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Kikimr\PBPublic\Api\Protos\YdbOperation::initOnce();
        \GPBMetadata\Kikimr\PBPublic\Api\Protos\YdbTable::initOnce();
        $pool->internalAddGeneratedFile(
            '
ó
6kikimr/public/api/protos/ydb_clickhouse_internal.protoYdb.ClickhouseInternal(kikimr/public/api/protos/ydb_table.proto"ú
ScanRequest9
operation_params (2.Ydb.Operations.OperationParams
table (	
columns (	
from_key (
from_key_inclusive (
to_key (
to_key_inclusive (
max_rows (
	max_bytes	 (
snapshot_id
 (	"<
ScanResponse,
	operation (2.Ydb.Operations.Operation"W

ScanResult
blocks (
eos (
last_key (
last_key_inclusive ("i
GetShardLocationsRequest9
operation_params (2.Ydb.Operations.OperationParams

tablet_ids ("I
GetShardLocationsResponse,
	operation (2.Ydb.Operations.Operation";

TabletInfo
	tablet_id (
host (	
port ("N
GetShardLocationsResult3
tablets (2".Ydb.ClickhouseInternal.TabletInfo"€
DescribeTableRequest9
operation_params (2.Ydb.Operations.OperationParams
path (	
include_partitions_info ("N
PartitionInfo
	tablet_id (
end_key (
end_key_inclusive ("¡
DescribeTableResult&
columns (2.Ydb.Table.ColumnMeta
primary_key (	9

partitions (2%.Ydb.ClickhouseInternal.PartitionInfo

is_virtual ("E
DescribeTableResponse,
	operation (2.Ydb.Operations.Operation"}
CreateSnapshotRequest9
operation_params (2.Ydb.Operations.OperationParams
path (	
ignore_system_views ("?
CreateSnapshotResult
snapshot_id (	

timeout_ms ("F
CreateSnapshotResponse,
	operation (2.Ydb.Operations.Operation"“
RefreshSnapshotRequest9
operation_params (2.Ydb.Operations.OperationParams
path (	
snapshot_id (	
ignore_system_views (",
RefreshSnapshotResult
snapshot_id (	"G
RefreshSnapshotResponse,
	operation (2.Ydb.Operations.Operation"“
DiscardSnapshotRequest9
operation_params (2.Ydb.Operations.OperationParams
path (	
snapshot_id (	
ignore_system_views (",
DiscardSnapshotResult
snapshot_id (	"G
DiscardSnapshotResponse,
	operation (2.Ydb.Operations.OperationB8
com.yandex.ydb.clickhouseBClickhouseInternalProtosøbproto3'
        , true);

        static::$is_initialized = true;
    }
}

