<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_coordination.proto

namespace Ydb\Coordination;

if (false) {
    /**
     * This class is deprecated. Use Ydb\Coordination\SessionRequest\DescribeSemaphore instead.
     * @deprecated
     */
    class SessionRequest_DescribeSemaphore {}
}
class_exists(SessionRequest\DescribeSemaphore::class);
@trigger_error('Ydb\Coordination\SessionRequest_DescribeSemaphore is deprecated and will be removed in the next major release. Use Ydb\Coordination\SessionRequest\DescribeSemaphore instead', E_USER_DEPRECATED);

