<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_coordination.proto

namespace Ydb\Coordination;

if (false) {
    /**
     * This class is deprecated. Use Ydb\Coordination\SessionRequest\DeleteSemaphore instead.
     * @deprecated
     */
    class SessionRequest_DeleteSemaphore {}
}
class_exists(SessionRequest\DeleteSemaphore::class);
@trigger_error('Ydb\Coordination\SessionRequest_DeleteSemaphore is deprecated and will be removed in the next major release. Use Ydb\Coordination\SessionRequest\DeleteSemaphore instead', E_USER_DEPRECATED);

