<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_coordination.proto

namespace Ydb\Coordination;

if (false) {
    /**
     * This class is deprecated. Use Ydb\Coordination\SessionResponse\SessionStopped instead.
     * @deprecated
     */
    class SessionResponse_SessionStopped {}
}
class_exists(SessionResponse\SessionStopped::class);
@trigger_error('Ydb\Coordination\SessionResponse_SessionStopped is deprecated and will be removed in the next major release. Use Ydb\Coordination\SessionResponse\SessionStopped instead', E_USER_DEPRECATED);

