<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_coordination.proto

namespace Ydb\Coordination;

if (false) {
    /**
     * This class is deprecated. Use Ydb\Coordination\SessionResponse\AcquireSemaphoreResult instead.
     * @deprecated
     */
    class SessionResponse_AcquireSemaphoreResult {}
}
class_exists(SessionResponse\AcquireSemaphoreResult::class);
@trigger_error('Ydb\Coordination\SessionResponse_AcquireSemaphoreResult is deprecated and will be removed in the next major release. Use Ydb\Coordination\SessionResponse\AcquireSemaphoreResult instead', E_USER_DEPRECATED);

