<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_coordination.proto

namespace Ydb\Coordination;

if (false) {
    /**
     * This class is deprecated. Use Ydb\Coordination\SessionRequest\ReleaseSemaphore instead.
     * @deprecated
     */
    class SessionRequest_ReleaseSemaphore {}
}
class_exists(SessionRequest\ReleaseSemaphore::class);
@trigger_error('Ydb\Coordination\SessionRequest_ReleaseSemaphore is deprecated and will be removed in the next major release. Use Ydb\Coordination\SessionRequest\ReleaseSemaphore instead', E_USER_DEPRECATED);

