<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_coordination.proto

namespace Ydb\Coordination;

if (false) {
    /**
     * This class is deprecated. Use Ydb\Coordination\SessionResponse\AcquireSemaphorePending instead.
     * @deprecated
     */
    class SessionResponse_AcquireSemaphorePending {}
}
class_exists(SessionResponse\AcquireSemaphorePending::class);
@trigger_error('Ydb\Coordination\SessionResponse_AcquireSemaphorePending is deprecated and will be removed in the next major release. Use Ydb\Coordination\SessionResponse\AcquireSemaphorePending instead', E_USER_DEPRECATED);

