<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_coordination.proto

namespace Ydb\Coordination;

if (false) {
    /**
     * This class is deprecated. Use Ydb\Coordination\SessionResponse\PingPong instead.
     * @deprecated
     */
    class SessionResponse_PingPong {}
}
class_exists(SessionResponse\PingPong::class);
@trigger_error('Ydb\Coordination\SessionResponse_PingPong is deprecated and will be removed in the next major release. Use Ydb\Coordination\SessionResponse\PingPong instead', E_USER_DEPRECATED);

