<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_coordination.proto

namespace Ydb\Coordination;

if (false) {
    /**
     * This class is deprecated. Use Ydb\Coordination\SessionRequest\SessionStart instead.
     * @deprecated
     */
    class SessionRequest_SessionStart {}
}
class_exists(SessionRequest\SessionStart::class);
@trigger_error('Ydb\Coordination\SessionRequest_SessionStart is deprecated and will be removed in the next major release. Use Ydb\Coordination\SessionRequest\SessionStart instead', E_USER_DEPRECATED);

