<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_table.proto

namespace Ydb\Table\ChangefeedDescription;

use UnexpectedValueException;

/**
 * Protobuf type <code>Ydb.Table.ChangefeedDescription.State</code>
 */
class State
{
    /**
     * Generated from protobuf enum <code>STATE_UNSPECIFIED = 0;</code>
     */
    const STATE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>STATE_ENABLED = 1;</code>
     */
    const STATE_ENABLED = 1;
    /**
     * Generated from protobuf enum <code>STATE_DISABLED = 2;</code>
     */
    const STATE_DISABLED = 2;

    private static $valueToName = [
        self::STATE_UNSPECIFIED => 'STATE_UNSPECIFIED',
        self::STATE_ENABLED => 'STATE_ENABLED',
        self::STATE_DISABLED => 'STATE_DISABLED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(State::class, \Ydb\Table\ChangefeedDescription_State::class);

