<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_import.proto

namespace Ydb\Import\ImportFromS3Settings;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Import.ImportFromS3Settings.Item</code>
 */
class Item extends \Google\Protobuf\Internal\Message
{
    /**
     * Database path to a database object to import the item to
     * Resolved relative to the default destination_path
     * May be omitted if the item's source_path is specified, in this case will be taken equal to it
     *
     * Generated from protobuf field <code>string destination_path = 2;</code>
     */
    protected $destination_path = '';
    protected $Source;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source_prefix
     *           The S3 object prefix can be either provided explicitly
     *     @type string $source_path
     *           Or, if the export contains the database objects list, you may specify the database object name, and the S3 prefix will be looked up in the database objects list by the import procedure
     *     @type string $destination_path
     *           Database path to a database object to import the item to
     *           Resolved relative to the default destination_path
     *           May be omitted if the item's source_path is specified, in this case will be taken equal to it
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbImport::initOnce();
        parent::__construct($data);
    }

    /**
     * The S3 object prefix can be either provided explicitly
     *
     * Generated from protobuf field <code>string source_prefix = 1;</code>
     * @return string
     */
    public function getSourcePrefix()
    {
        return $this->readOneof(1);
    }

    public function hasSourcePrefix()
    {
        return $this->hasOneof(1);
    }

    /**
     * The S3 object prefix can be either provided explicitly
     *
     * Generated from protobuf field <code>string source_prefix = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSourcePrefix($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Or, if the export contains the database objects list, you may specify the database object name, and the S3 prefix will be looked up in the database objects list by the import procedure
     *
     * Generated from protobuf field <code>string source_path = 3;</code>
     * @return string
     */
    public function getSourcePath()
    {
        return $this->readOneof(3);
    }

    public function hasSourcePath()
    {
        return $this->hasOneof(3);
    }

    /**
     * Or, if the export contains the database objects list, you may specify the database object name, and the S3 prefix will be looked up in the database objects list by the import procedure
     *
     * Generated from protobuf field <code>string source_path = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSourcePath($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Database path to a database object to import the item to
     * Resolved relative to the default destination_path
     * May be omitted if the item's source_path is specified, in this case will be taken equal to it
     *
     * Generated from protobuf field <code>string destination_path = 2;</code>
     * @return string
     */
    public function getDestinationPath()
    {
        return $this->destination_path;
    }

    /**
     * Database path to a database object to import the item to
     * Resolved relative to the default destination_path
     * May be omitted if the item's source_path is specified, in this case will be taken equal to it
     *
     * Generated from protobuf field <code>string destination_path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDestinationPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->destination_path = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getSource()
    {
        return $this->whichOneof("Source");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Item::class, \Ydb\Import\ImportFromS3Settings_Item::class);

