<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_import.proto

namespace Ydb\Import\ImportFromS3Settings;

use UnexpectedValueException;

/**
 * Protobuf type <code>Ydb.Import.ImportFromS3Settings.Scheme</code>
 */
class Scheme
{
    /**
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>HTTP = 1;</code>
     */
    const HTTP = 1;
    /**
     * Generated from protobuf enum <code>HTTPS = 2;</code>
     */
    const HTTPS = 2;

    private static $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::HTTP => 'HTTP',
        self::HTTPS => 'HTTPS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Scheme::class, \Ydb\Import\ImportFromS3Settings_Scheme::class);

