<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_topic.proto

namespace Ydb\Topic\AddOffsetsToTransactionRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Topic.AddOffsetsToTransactionRequest.TopicOffsets</code>
 */
class TopicOffsets extends \Google\Protobuf\Internal\Message
{
    /**
     * Topic path.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     */
    protected $path = '';
    /**
     * Ranges of offsets by partitions.
     *
     * Generated from protobuf field <code>repeated .Ydb.Topic.AddOffsetsToTransactionRequest.TopicOffsets.PartitionOffsets partitions = 2;</code>
     */
    private $partitions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *           Topic path.
     *     @type array<\Ydb\Topic\AddOffsetsToTransactionRequest\TopicOffsets\PartitionOffsets>|\Google\Protobuf\Internal\RepeatedField $partitions
     *           Ranges of offsets by partitions.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTopic::initOnce();
        parent::__construct($data);
    }

    /**
     * Topic path.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Topic path.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Ranges of offsets by partitions.
     *
     * Generated from protobuf field <code>repeated .Ydb.Topic.AddOffsetsToTransactionRequest.TopicOffsets.PartitionOffsets partitions = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPartitions()
    {
        return $this->partitions;
    }

    /**
     * Ranges of offsets by partitions.
     *
     * Generated from protobuf field <code>repeated .Ydb.Topic.AddOffsetsToTransactionRequest.TopicOffsets.PartitionOffsets partitions = 2;</code>
     * @param array<\Ydb\Topic\AddOffsetsToTransactionRequest\TopicOffsets\PartitionOffsets>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPartitions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ydb\Topic\AddOffsetsToTransactionRequest\TopicOffsets\PartitionOffsets::class);
        $this->partitions = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TopicOffsets::class, \Ydb\Topic\AddOffsetsToTransactionRequest_TopicOffsets::class);

