<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_discovery.proto

namespace Ydb\Discovery;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Discovery.EndpointInfo</code>
 */
class EndpointInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string address = 1;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     */
    protected $port = 0;
    /**
     * Generated from protobuf field <code>float load_factor = 3;</code>
     */
    protected $load_factor = 0.0;
    /**
     * Generated from protobuf field <code>bool ssl = 4;</code>
     */
    protected $ssl = false;
    /**
     * Generated from protobuf field <code>repeated string service = 5;</code>
     */
    private $service;
    /**
     * Generated from protobuf field <code>string location = 6;</code>
     */
    protected $location = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *     @type int $port
     *     @type float $load_factor
     *     @type bool $ssl
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $service
     *     @type string $location
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kikimr\PBPublic\Api\Protos\YdbDiscovery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     * @return int
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float load_factor = 3;</code>
     * @return float
     */
    public function getLoadFactor()
    {
        return $this->load_factor;
    }

    /**
     * Generated from protobuf field <code>float load_factor = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setLoadFactor($var)
    {
        GPBUtil::checkFloat($var);
        $this->load_factor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ssl = 4;</code>
     * @return bool
     */
    public function getSsl()
    {
        return $this->ssl;
    }

    /**
     * Generated from protobuf field <code>bool ssl = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setSsl($var)
    {
        GPBUtil::checkBool($var);
        $this->ssl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string service = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>repeated string service = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setService($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->service = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string location = 6;</code>
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>string location = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->location = $var;

        return $this;
    }

}

