<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_discovery.proto

namespace Ydb\Discovery;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Discovery.ListEndpointsResult</code>
 */
class ListEndpointsResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Ydb.Discovery.EndpointInfo endpoints = 1;</code>
     */
    private $endpoints;
    /**
     * Generated from protobuf field <code>string self_location = 2;</code>
     */
    protected $self_location = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Ydb\Discovery\EndpointInfo>|\Google\Protobuf\Internal\RepeatedField $endpoints
     *     @type string $self_location
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbDiscovery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.Discovery.EndpointInfo endpoints = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEndpoints()
    {
        return $this->endpoints;
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.Discovery.EndpointInfo endpoints = 1;</code>
     * @param array<\Ydb\Discovery\EndpointInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEndpoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ydb\Discovery\EndpointInfo::class);
        $this->endpoints = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string self_location = 2;</code>
     * @return string
     */
    public function getSelfLocation()
    {
        return $this->self_location;
    }

    /**
     * Generated from protobuf field <code>string self_location = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSelfLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->self_location = $var;

        return $this;
    }

}

