<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_discovery.proto

namespace Ydb\Discovery;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Discovery.NodeRegistrationRequest</code>
 */
class NodeRegistrationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string host = 1;</code>
     */
    protected $host = null;
    /**
     * Generated from protobuf field <code>optional uint32 port = 2;</code>
     */
    protected $port = null;
    /**
     * Generated from protobuf field <code>optional string resolve_host = 3;</code>
     */
    protected $resolve_host = null;
    /**
     * Generated from protobuf field <code>optional string address = 4;</code>
     */
    protected $address = null;
    /**
     * Generated from protobuf field <code>optional .Ydb.Discovery.NodeLocation location = 5;</code>
     */
    protected $location = null;
    /**
     * Generated from protobuf field <code>optional string domain_path = 6;</code>
     */
    protected $domain_path = null;
    /**
     * Generated from protobuf field <code>optional bool fixed_node_id = 7;</code>
     */
    protected $fixed_node_id = null;
    /**
     * Generated from protobuf field <code>optional string path = 8;</code>
     */
    protected $path = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $host
     *     @type int $port
     *     @type string $resolve_host
     *     @type string $address
     *     @type \Ydb\Discovery\NodeLocation $location
     *     @type string $domain_path
     *     @type bool $fixed_node_id
     *     @type string $path
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbDiscovery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string host = 1;</code>
     * @return string
     */
    public function getHost()
    {
        return isset($this->host) ? $this->host : '';
    }

    public function hasHost()
    {
        return isset($this->host);
    }

    public function clearHost()
    {
        unset($this->host);
    }

    /**
     * Generated from protobuf field <code>optional string host = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 port = 2;</code>
     * @return int
     */
    public function getPort()
    {
        return isset($this->port) ? $this->port : 0;
    }

    public function hasPort()
    {
        return isset($this->port);
    }

    public function clearPort()
    {
        unset($this->port);
    }

    /**
     * Generated from protobuf field <code>optional uint32 port = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string resolve_host = 3;</code>
     * @return string
     */
    public function getResolveHost()
    {
        return isset($this->resolve_host) ? $this->resolve_host : '';
    }

    public function hasResolveHost()
    {
        return isset($this->resolve_host);
    }

    public function clearResolveHost()
    {
        unset($this->resolve_host);
    }

    /**
     * Generated from protobuf field <code>optional string resolve_host = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setResolveHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->resolve_host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string address = 4;</code>
     * @return string
     */
    public function getAddress()
    {
        return isset($this->address) ? $this->address : '';
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>optional string address = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Ydb.Discovery.NodeLocation location = 5;</code>
     * @return \Ydb\Discovery\NodeLocation|null
     */
    public function getLocation()
    {
        return $this->location;
    }

    public function hasLocation()
    {
        return isset($this->location);
    }

    public function clearLocation()
    {
        unset($this->location);
    }

    /**
     * Generated from protobuf field <code>optional .Ydb.Discovery.NodeLocation location = 5;</code>
     * @param \Ydb\Discovery\NodeLocation $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Discovery\NodeLocation::class);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string domain_path = 6;</code>
     * @return string
     */
    public function getDomainPath()
    {
        return isset($this->domain_path) ? $this->domain_path : '';
    }

    public function hasDomainPath()
    {
        return isset($this->domain_path);
    }

    public function clearDomainPath()
    {
        unset($this->domain_path);
    }

    /**
     * Generated from protobuf field <code>optional string domain_path = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDomainPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->domain_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool fixed_node_id = 7;</code>
     * @return bool
     */
    public function getFixedNodeId()
    {
        return isset($this->fixed_node_id) ? $this->fixed_node_id : false;
    }

    public function hasFixedNodeId()
    {
        return isset($this->fixed_node_id);
    }

    public function clearFixedNodeId()
    {
        unset($this->fixed_node_id);
    }

    /**
     * Generated from protobuf field <code>optional bool fixed_node_id = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setFixedNodeId($var)
    {
        GPBUtil::checkBool($var);
        $this->fixed_node_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string path = 8;</code>
     * @return string
     */
    public function getPath()
    {
        return isset($this->path) ? $this->path : '';
    }

    public function hasPath()
    {
        return isset($this->path);
    }

    public function clearPath()
    {
        unset($this->path);
    }

    /**
     * Generated from protobuf field <code>optional string path = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

}

