<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_import.proto

namespace Ydb\Import;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Import.ImportFromS3Metadata</code>
 */
class ImportFromS3Metadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Ydb.Import.ImportFromS3Settings settings = 1;</code>
     */
    protected $settings = null;
    /**
     * Generated from protobuf field <code>.Ydb.Import.ImportProgress.Progress progress = 2;</code>
     */
    protected $progress = 0;
    /**
     * Generated from protobuf field <code>repeated .Ydb.Import.ImportItemProgress items_progress = 3;</code>
     */
    private $items_progress;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ydb\Import\ImportFromS3Settings $settings
     *     @type int $progress
     *     @type array<\Ydb\Import\ImportItemProgress>|\Google\Protobuf\Internal\RepeatedField $items_progress
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbImport::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Import.ImportFromS3Settings settings = 1;</code>
     * @return \Ydb\Import\ImportFromS3Settings|null
     */
    public function getSettings()
    {
        return $this->settings;
    }

    public function hasSettings()
    {
        return isset($this->settings);
    }

    public function clearSettings()
    {
        unset($this->settings);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Import.ImportFromS3Settings settings = 1;</code>
     * @param \Ydb\Import\ImportFromS3Settings $var
     * @return $this
     */
    public function setSettings($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Import\ImportFromS3Settings::class);
        $this->settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Import.ImportProgress.Progress progress = 2;</code>
     * @return int
     */
    public function getProgress()
    {
        return $this->progress;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Import.ImportProgress.Progress progress = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setProgress($var)
    {
        GPBUtil::checkEnum($var, \Ydb\Import\ImportProgress\Progress::class);
        $this->progress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.Import.ImportItemProgress items_progress = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItemsProgress()
    {
        return $this->items_progress;
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.Import.ImportItemProgress items_progress = 3;</code>
     * @param array<\Ydb\Import\ImportItemProgress>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItemsProgress($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ydb\Import\ImportItemProgress::class);
        $this->items_progress = $arr;

        return $this;
    }

}

