<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_import.proto

namespace Ydb\Import;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Import.ListObjectsInFsExportSettings</code>
 */
class ListObjectsInFsExportSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string base_path = 1 [(.Ydb.required) = true];</code>
     */
    protected $base_path = '';
    /**
     * Generated from protobuf field <code>repeated .Ydb.Import.ListObjectsInFsExportSettings.Item items = 2;</code>
     */
    private $items;
    /**
     * Generated from protobuf field <code>uint32 number_of_retries = 3;</code>
     */
    protected $number_of_retries = 0;
    /**
     * Settings how data is encrypted.
     * If encryption_settings field is not specified,
     * the resulting data is considered not encrypted.
     *
     * Generated from protobuf field <code>.Ydb.Export.EncryptionSettings encryption_settings = 4;</code>
     */
    protected $encryption_settings = null;
    /**
     * Patterns (PCRE) for paths excluded from import operation.
     * - Patterns are matched against the database object names stored in the backup listing.
     * - Object is excluded from import operation if it matches any of the specified exclude regexps.
     *
     * Generated from protobuf field <code>repeated string exclude_regexps = 5;</code>
     */
    private $exclude_regexps;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $base_path
     *     @type array<\Ydb\Import\ListObjectsInFsExportSettings\Item>|\Google\Protobuf\Internal\RepeatedField $items
     *     @type int $number_of_retries
     *     @type \Ydb\Export\EncryptionSettings $encryption_settings
     *           Settings how data is encrypted.
     *           If encryption_settings field is not specified,
     *           the resulting data is considered not encrypted.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $exclude_regexps
     *           Patterns (PCRE) for paths excluded from import operation.
     *           - Patterns are matched against the database object names stored in the backup listing.
     *           - Object is excluded from import operation if it matches any of the specified exclude regexps.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbImport::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string base_path = 1 [(.Ydb.required) = true];</code>
     * @return string
     */
    public function getBasePath()
    {
        return $this->base_path;
    }

    /**
     * Generated from protobuf field <code>string base_path = 1 [(.Ydb.required) = true];</code>
     * @param string $var
     * @return $this
     */
    public function setBasePath($var)
    {
        GPBUtil::checkString($var, True);
        $this->base_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.Import.ListObjectsInFsExportSettings.Item items = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.Import.ListObjectsInFsExportSettings.Item items = 2;</code>
     * @param array<\Ydb\Import\ListObjectsInFsExportSettings\Item>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ydb\Import\ListObjectsInFsExportSettings\Item::class);
        $this->items = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 number_of_retries = 3;</code>
     * @return int
     */
    public function getNumberOfRetries()
    {
        return $this->number_of_retries;
    }

    /**
     * Generated from protobuf field <code>uint32 number_of_retries = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setNumberOfRetries($var)
    {
        GPBUtil::checkUint32($var);
        $this->number_of_retries = $var;

        return $this;
    }

    /**
     * Settings how data is encrypted.
     * If encryption_settings field is not specified,
     * the resulting data is considered not encrypted.
     *
     * Generated from protobuf field <code>.Ydb.Export.EncryptionSettings encryption_settings = 4;</code>
     * @return \Ydb\Export\EncryptionSettings|null
     */
    public function getEncryptionSettings()
    {
        return $this->encryption_settings;
    }

    public function hasEncryptionSettings()
    {
        return isset($this->encryption_settings);
    }

    public function clearEncryptionSettings()
    {
        unset($this->encryption_settings);
    }

    /**
     * Settings how data is encrypted.
     * If encryption_settings field is not specified,
     * the resulting data is considered not encrypted.
     *
     * Generated from protobuf field <code>.Ydb.Export.EncryptionSettings encryption_settings = 4;</code>
     * @param \Ydb\Export\EncryptionSettings $var
     * @return $this
     */
    public function setEncryptionSettings($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Export\EncryptionSettings::class);
        $this->encryption_settings = $var;

        return $this;
    }

    /**
     * Patterns (PCRE) for paths excluded from import operation.
     * - Patterns are matched against the database object names stored in the backup listing.
     * - Object is excluded from import operation if it matches any of the specified exclude regexps.
     *
     * Generated from protobuf field <code>repeated string exclude_regexps = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExcludeRegexps()
    {
        return $this->exclude_regexps;
    }

    /**
     * Patterns (PCRE) for paths excluded from import operation.
     * - Patterns are matched against the database object names stored in the backup listing.
     * - Object is excluded from import operation if it matches any of the specified exclude regexps.
     *
     * Generated from protobuf field <code>repeated string exclude_regexps = 5;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExcludeRegexps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->exclude_regexps = $arr;

        return $this;
    }

}

