<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_bridge_common.proto

namespace Ydb\Bridge;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describes the state of a single pile within the cluster
 *
 * Generated from protobuf message <code>Ydb.Bridge.PileState</code>
 */
class PileState extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the pile
     *
     * Generated from protobuf field <code>string pile_name = 1 [(.Ydb.length) = {</code>
     */
    protected $pile_name = '';
    /**
     * The operational state of the pile
     *
     * Generated from protobuf field <code>.Ydb.Bridge.PileState.State state = 2;</code>
     */
    protected $state = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $pile_name
     *           The name of the pile
     *     @type int $state
     *           The operational state of the pile
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbBridgeCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the pile
     *
     * Generated from protobuf field <code>string pile_name = 1 [(.Ydb.length) = {</code>
     * @return string
     */
    public function getPileName()
    {
        return $this->pile_name;
    }

    /**
     * The name of the pile
     *
     * Generated from protobuf field <code>string pile_name = 1 [(.Ydb.length) = {</code>
     * @param string $var
     * @return $this
     */
    public function setPileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->pile_name = $var;

        return $this;
    }

    /**
     * The operational state of the pile
     *
     * Generated from protobuf field <code>.Ydb.Bridge.PileState.State state = 2;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * The operational state of the pile
     *
     * Generated from protobuf field <code>.Ydb.Bridge.PileState.State state = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Ydb\Bridge\PileState\State::class);
        $this->state = $var;

        return $this;
    }

}

