<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_formats.proto

namespace Ydb\Formats;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Formats.CsvSettings</code>
 */
class CsvSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Number of rows to skip before CSV data. It should be present only in the first upsert of CSV file.
     *
     * Generated from protobuf field <code>uint32 skip_rows = 1;</code>
     */
    protected $skip_rows = 0;
    /**
     * Fields delimiter in CSV file. It's "," if not set.
     *
     * Generated from protobuf field <code>bytes delimiter = 2;</code>
     */
    protected $delimiter = '';
    /**
     * String value that would be interpreted as NULL.
     *
     * Generated from protobuf field <code>bytes null_value = 3;</code>
     */
    protected $null_value = '';
    /**
     * First not skipped line is a CSV header (list of column names).
     *
     * Generated from protobuf field <code>bool header = 4;</code>
     */
    protected $header = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $skip_rows
     *           Number of rows to skip before CSV data. It should be present only in the first upsert of CSV file.
     *     @type string $delimiter
     *           Fields delimiter in CSV file. It's "," if not set.
     *     @type string $null_value
     *           String value that would be interpreted as NULL.
     *     @type bool $header
     *           First not skipped line is a CSV header (list of column names).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbFormats::initOnce();
        parent::__construct($data);
    }

    /**
     * Number of rows to skip before CSV data. It should be present only in the first upsert of CSV file.
     *
     * Generated from protobuf field <code>uint32 skip_rows = 1;</code>
     * @return int
     */
    public function getSkipRows()
    {
        return $this->skip_rows;
    }

    /**
     * Number of rows to skip before CSV data. It should be present only in the first upsert of CSV file.
     *
     * Generated from protobuf field <code>uint32 skip_rows = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSkipRows($var)
    {
        GPBUtil::checkUint32($var);
        $this->skip_rows = $var;

        return $this;
    }

    /**
     * Fields delimiter in CSV file. It's "," if not set.
     *
     * Generated from protobuf field <code>bytes delimiter = 2;</code>
     * @return string
     */
    public function getDelimiter()
    {
        return $this->delimiter;
    }

    /**
     * Fields delimiter in CSV file. It's "," if not set.
     *
     * Generated from protobuf field <code>bytes delimiter = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDelimiter($var)
    {
        GPBUtil::checkString($var, False);
        $this->delimiter = $var;

        return $this;
    }

    /**
     * String value that would be interpreted as NULL.
     *
     * Generated from protobuf field <code>bytes null_value = 3;</code>
     * @return string
     */
    public function getNullValue()
    {
        return $this->null_value;
    }

    /**
     * String value that would be interpreted as NULL.
     *
     * Generated from protobuf field <code>bytes null_value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNullValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->null_value = $var;

        return $this;
    }

    /**
     * First not skipped line is a CSV header (list of column names).
     *
     * Generated from protobuf field <code>bool header = 4;</code>
     * @return bool
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * First not skipped line is a CSV header (list of column names).
     *
     * Generated from protobuf field <code>bool header = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkBool($var);
        $this->header = $var;

        return $this;
    }

}

