<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_topic.proto

namespace Ydb\Topic\StreamDirectReadMessage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Messages that have been read directly from the partition node.
 * It's a response to StreamRead.ReadRequest
 *
 * Generated from protobuf message <code>Ydb.Topic.StreamDirectReadMessage.DirectReadResponse</code>
 */
class DirectReadResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Partition session identifier.
     *
     * Generated from protobuf field <code>int64 partition_session_id = 1;</code>
     */
    protected $partition_session_id = 0;
    /**
     * Read request identifier.
     *
     * Generated from protobuf field <code>int64 direct_read_id = 2;</code>
     */
    protected $direct_read_id = 0;
    /**
     * Messages data
     *
     * Generated from protobuf field <code>.Ydb.Topic.StreamReadMessage.ReadResponse.PartitionData partition_data = 3;</code>
     */
    protected $partition_data = null;
    /**
     * Total size in bytes of this response as calculated by server.
     * See ReadRequest comment above.
     *
     * Generated from protobuf field <code>int64 bytes_size = 4;</code>
     */
    protected $bytes_size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $partition_session_id
     *           Partition session identifier.
     *     @type int|string $direct_read_id
     *           Read request identifier.
     *     @type \Ydb\Topic\StreamReadMessage\ReadResponse\PartitionData $partition_data
     *           Messages data
     *     @type int|string $bytes_size
     *           Total size in bytes of this response as calculated by server.
     *           See ReadRequest comment above.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTopic::initOnce();
        parent::__construct($data);
    }

    /**
     * Partition session identifier.
     *
     * Generated from protobuf field <code>int64 partition_session_id = 1;</code>
     * @return int|string
     */
    public function getPartitionSessionId()
    {
        return $this->partition_session_id;
    }

    /**
     * Partition session identifier.
     *
     * Generated from protobuf field <code>int64 partition_session_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPartitionSessionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->partition_session_id = $var;

        return $this;
    }

    /**
     * Read request identifier.
     *
     * Generated from protobuf field <code>int64 direct_read_id = 2;</code>
     * @return int|string
     */
    public function getDirectReadId()
    {
        return $this->direct_read_id;
    }

    /**
     * Read request identifier.
     *
     * Generated from protobuf field <code>int64 direct_read_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDirectReadId($var)
    {
        GPBUtil::checkInt64($var);
        $this->direct_read_id = $var;

        return $this;
    }

    /**
     * Messages data
     *
     * Generated from protobuf field <code>.Ydb.Topic.StreamReadMessage.ReadResponse.PartitionData partition_data = 3;</code>
     * @return \Ydb\Topic\StreamReadMessage\ReadResponse\PartitionData|null
     */
    public function getPartitionData()
    {
        return $this->partition_data;
    }

    public function hasPartitionData()
    {
        return isset($this->partition_data);
    }

    public function clearPartitionData()
    {
        unset($this->partition_data);
    }

    /**
     * Messages data
     *
     * Generated from protobuf field <code>.Ydb.Topic.StreamReadMessage.ReadResponse.PartitionData partition_data = 3;</code>
     * @param \Ydb\Topic\StreamReadMessage\ReadResponse\PartitionData $var
     * @return $this
     */
    public function setPartitionData($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Topic\StreamReadMessage\ReadResponse\PartitionData::class);
        $this->partition_data = $var;

        return $this;
    }

    /**
     * Total size in bytes of this response as calculated by server.
     * See ReadRequest comment above.
     *
     * Generated from protobuf field <code>int64 bytes_size = 4;</code>
     * @return int|string
     */
    public function getBytesSize()
    {
        return $this->bytes_size;
    }

    /**
     * Total size in bytes of this response as calculated by server.
     * See ReadRequest comment above.
     *
     * Generated from protobuf field <code>int64 bytes_size = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBytesSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->bytes_size = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(DirectReadResponse::class, \Ydb\Topic\StreamDirectReadMessage_DirectReadResponse::class);

