<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_topic.proto

namespace Ydb\Topic\StreamDirectReadMessage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Client-server message for direct read session.
 *     InitRequest - command from client to create and start a direct read session.
 *     StartDirectReadPartitionSessionRequest - command from client to create and start a direct read partition session.
 *         Client signals it is ready to get data from partition.
 *     UpdateTokenRequest - request to update auth token
 *
 * Generated from protobuf message <code>Ydb.Topic.StreamDirectReadMessage.FromClient</code>
 */
class FromClient extends \Google\Protobuf\Internal\Message
{
    protected $client_message;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ydb\Topic\StreamDirectReadMessage\InitRequest $init_request
     *     @type \Ydb\Topic\StreamDirectReadMessage\StartDirectReadPartitionSessionRequest $start_direct_read_partition_session_request
     *     @type \Ydb\Topic\UpdateTokenRequest $update_token_request
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTopic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Topic.StreamDirectReadMessage.InitRequest init_request = 1;</code>
     * @return \Ydb\Topic\StreamDirectReadMessage\InitRequest|null
     */
    public function getInitRequest()
    {
        return $this->readOneof(1);
    }

    public function hasInitRequest()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Topic.StreamDirectReadMessage.InitRequest init_request = 1;</code>
     * @param \Ydb\Topic\StreamDirectReadMessage\InitRequest $var
     * @return $this
     */
    public function setInitRequest($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Topic\StreamDirectReadMessage\InitRequest::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Topic.StreamDirectReadMessage.StartDirectReadPartitionSessionRequest start_direct_read_partition_session_request = 2;</code>
     * @return \Ydb\Topic\StreamDirectReadMessage\StartDirectReadPartitionSessionRequest|null
     */
    public function getStartDirectReadPartitionSessionRequest()
    {
        return $this->readOneof(2);
    }

    public function hasStartDirectReadPartitionSessionRequest()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Topic.StreamDirectReadMessage.StartDirectReadPartitionSessionRequest start_direct_read_partition_session_request = 2;</code>
     * @param \Ydb\Topic\StreamDirectReadMessage\StartDirectReadPartitionSessionRequest $var
     * @return $this
     */
    public function setStartDirectReadPartitionSessionRequest($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Topic\StreamDirectReadMessage\StartDirectReadPartitionSessionRequest::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Topic.UpdateTokenRequest update_token_request = 3;</code>
     * @return \Ydb\Topic\UpdateTokenRequest|null
     */
    public function getUpdateTokenRequest()
    {
        return $this->readOneof(3);
    }

    public function hasUpdateTokenRequest()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Topic.UpdateTokenRequest update_token_request = 3;</code>
     * @param \Ydb\Topic\UpdateTokenRequest $var
     * @return $this
     */
    public function setUpdateTokenRequest($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Topic\UpdateTokenRequest::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getClientMessage()
    {
        return $this->whichOneof("client_message");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(FromClient::class, \Ydb\Topic\StreamDirectReadMessage_FromClient::class);

