<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_topic.proto

namespace Ydb\Topic\StreamDirectReadMessage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Signal for server that client is ready to receive data for partition.
 *
 * Generated from protobuf message <code>Ydb.Topic.StreamDirectReadMessage.StartDirectReadPartitionSessionResponse</code>
 */
class StartDirectReadPartitionSessionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Partition session identifier of partition to start read.
     *
     * Generated from protobuf field <code>int64 partition_session_id = 1;</code>
     */
    protected $partition_session_id = 0;
    /**
     * Partition generation.
     *
     * Generated from protobuf field <code>int64 generation = 2;</code>
     */
    protected $generation = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $partition_session_id
     *           Partition session identifier of partition to start read.
     *     @type int|string $generation
     *           Partition generation.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTopic::initOnce();
        parent::__construct($data);
    }

    /**
     * Partition session identifier of partition to start read.
     *
     * Generated from protobuf field <code>int64 partition_session_id = 1;</code>
     * @return int|string
     */
    public function getPartitionSessionId()
    {
        return $this->partition_session_id;
    }

    /**
     * Partition session identifier of partition to start read.
     *
     * Generated from protobuf field <code>int64 partition_session_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPartitionSessionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->partition_session_id = $var;

        return $this;
    }

    /**
     * Partition generation.
     *
     * Generated from protobuf field <code>int64 generation = 2;</code>
     * @return int|string
     */
    public function getGeneration()
    {
        return $this->generation;
    }

    /**
     * Partition generation.
     *
     * Generated from protobuf field <code>int64 generation = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGeneration($var)
    {
        GPBUtil::checkInt64($var);
        $this->generation = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(StartDirectReadPartitionSessionResponse::class, \Ydb\Topic\StreamDirectReadMessage_StartDirectReadPartitionSessionResponse::class);

