<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_scripting.proto

namespace Ydb\Scripting;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Contains result set (or a result set part) for one data or scan query in the script.
 * One result set can be split into several responses with same result_index.
 * Only the final response can contain query stats.
 *
 * Generated from protobuf message <code>Ydb.Scripting.ExecuteYqlPartialResult</code>
 */
class ExecuteYqlPartialResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Index of current result
     *
     * Generated from protobuf field <code>uint32 result_set_index = 1;</code>
     */
    protected $result_set_index = 0;
    /**
     * Result set (or a result set part) for one data or scan query
     *
     * Generated from protobuf field <code>.Ydb.ResultSet result_set = 2;</code>
     */
    protected $result_set = null;
    /**
     * Generated from protobuf field <code>.Ydb.TableStats.QueryStats query_stats = 3;</code>
     */
    protected $query_stats = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $result_set_index
     *           Index of current result
     *     @type \Ydb\ResultSet $result_set
     *           Result set (or a result set part) for one data or scan query
     *     @type \Ydb\TableStats\QueryStats $query_stats
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbScripting::initOnce();
        parent::__construct($data);
    }

    /**
     * Index of current result
     *
     * Generated from protobuf field <code>uint32 result_set_index = 1;</code>
     * @return int
     */
    public function getResultSetIndex()
    {
        return $this->result_set_index;
    }

    /**
     * Index of current result
     *
     * Generated from protobuf field <code>uint32 result_set_index = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResultSetIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->result_set_index = $var;

        return $this;
    }

    /**
     * Result set (or a result set part) for one data or scan query
     *
     * Generated from protobuf field <code>.Ydb.ResultSet result_set = 2;</code>
     * @return \Ydb\ResultSet|null
     */
    public function getResultSet()
    {
        return $this->result_set;
    }

    public function hasResultSet()
    {
        return isset($this->result_set);
    }

    public function clearResultSet()
    {
        unset($this->result_set);
    }

    /**
     * Result set (or a result set part) for one data or scan query
     *
     * Generated from protobuf field <code>.Ydb.ResultSet result_set = 2;</code>
     * @param \Ydb\ResultSet $var
     * @return $this
     */
    public function setResultSet($var)
    {
        GPBUtil::checkMessage($var, \Ydb\ResultSet::class);
        $this->result_set = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.TableStats.QueryStats query_stats = 3;</code>
     * @return \Ydb\TableStats\QueryStats|null
     */
    public function getQueryStats()
    {
        return $this->query_stats;
    }

    public function hasQueryStats()
    {
        return isset($this->query_stats);
    }

    public function clearQueryStats()
    {
        unset($this->query_stats);
    }

    /**
     * Generated from protobuf field <code>.Ydb.TableStats.QueryStats query_stats = 3;</code>
     * @param \Ydb\TableStats\QueryStats $var
     * @return $this
     */
    public function setQueryStats($var)
    {
        GPBUtil::checkMessage($var, \Ydb\TableStats\QueryStats::class);
        $this->query_stats = $var;

        return $this;
    }

}

