<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_scripting.proto

namespace Ydb\Scripting;

if (false) {
    /**
     * This class is deprecated. Use Ydb\Scripting\ExplainYqlRequest\Mode instead.
     * @deprecated
     */
    class ExplainYqlRequest_Mode {}
}
class_exists(ExplainYqlRequest\Mode::class);
@trigger_error('Ydb\Scripting\ExplainYqlRequest_Mode is deprecated and will be removed in the next major release. Use Ydb\Scripting\ExplainYqlRequest\Mode instead', E_USER_DEPRECATED);

