<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_federation_discovery.proto

namespace Ydb\FederationDiscovery\DatabaseInfo;

use UnexpectedValueException;

/**
 * Protobuf type <code>Ydb.FederationDiscovery.DatabaseInfo.Status</code>
 */
class Status
{
    /**
     * Generated from protobuf enum <code>STATUS_UNSPECIFIED = 0;</code>
     */
    const STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>AVAILABLE = 1;</code>
     */
    const AVAILABLE = 1;
    /**
     * Generated from protobuf enum <code>READ_ONLY = 2;</code>
     */
    const READ_ONLY = 2;
    /**
     * Generated from protobuf enum <code>UNAVAILABLE = 3;</code>
     */
    const UNAVAILABLE = 3;

    private static $valueToName = [
        self::STATUS_UNSPECIFIED => 'STATUS_UNSPECIFIED',
        self::AVAILABLE => 'AVAILABLE',
        self::READ_ONLY => 'READ_ONLY',
        self::UNAVAILABLE => 'UNAVAILABLE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Status::class, \Ydb\FederationDiscovery\DatabaseInfo_Status::class);

