name: ydb-php-examples
services:
  ydb-local:
    image: cr.yandex/yc/yandex-docker-local-ydb:latest
    ports:
      - 127.0.0.1:2135:2135
      - 127.0.0.1:2136:2136
      - 127.0.0.1:8765:8765
    volumes:
      # - ./ydb_data:/ydb_data
      - ./ydb_certs:/ydb_certs
    environment:
      GRPC_TLS_PORT: 2135
      GRPC_PORT: 2136
      MON_PORT: 8765
      YDB_DEFAULT_LOG_LEVEL: NOTICE
      YDB_USE_IN_MEMORY_PDISKS: true
  ydb-app:
    image: thecodingmachine/php:8.0-v4-cli
    depends_on:
      - ydb-local
    volumes:
      - .:/usr/src/app
    command: sh -c "composer install && php console select1"
    environment:
      PHP_EXTENSION_GRPC: 1
      PHP_EXTENSION_BCMATH: 1
      DB_ENDPOINT: ydb-local:2136
      DB_DATABASE: /local
      YDB_ANONYMOUS: true
      YDB_INSECURE: true

