<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_common.proto

namespace Ydb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.CostInfo</code>
 */
class CostInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Total amount of request units (RU), consumed by the operation.
     *
     * Generated from protobuf field <code>double consumed_units = 1;</code>
     */
    protected $consumed_units = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $consumed_units
     *           Total amount of request units (RU), consumed by the operation.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Total amount of request units (RU), consumed by the operation.
     *
     * Generated from protobuf field <code>double consumed_units = 1;</code>
     * @return float
     */
    public function getConsumedUnits()
    {
        return $this->consumed_units;
    }

    /**
     * Total amount of request units (RU), consumed by the operation.
     *
     * Generated from protobuf field <code>double consumed_units = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setConsumedUnits($var)
    {
        GPBUtil::checkDouble($var);
        $this->consumed_units = $var;

        return $this;
    }

}

