<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_value.proto

namespace Ydb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.DecimalType</code>
 */
class DecimalType extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 precision = 1;</code>
     */
    protected $precision = 0;
    /**
     * Generated from protobuf field <code>uint32 scale = 2;</code>
     */
    protected $scale = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $precision
     *     @type int $scale
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbValue::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 precision = 1;</code>
     * @return int
     */
    public function getPrecision()
    {
        return $this->precision;
    }

    /**
     * Generated from protobuf field <code>uint32 precision = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPrecision($var)
    {
        GPBUtil::checkUint32($var);
        $this->precision = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 scale = 2;</code>
     * @return int
     */
    public function getScale()
    {
        return $this->scale;
    }

    /**
     * Generated from protobuf field <code>uint32 scale = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setScale($var)
    {
        GPBUtil::checkUint32($var);
        $this->scale = $var;

        return $this;
    }

}

