<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_value.proto

namespace Ydb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.PgType</code>
 */
class PgType extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string type_name = 10;</code>
     */
    protected $type_name = '';
    /**
     * Generated from protobuf field <code>string type_modifier = 11;</code>
     */
    protected $type_modifier = '';
    /**
     * pg object id of the type
     * full registry could be found here: https://github.com/postgres/postgres/blob/master/src/include/catalog/pg_type.dat
     *
     * Generated from protobuf field <code>uint32 oid = 1;</code>
     */
    protected $oid = 0;
    /**
     * advanced type details useful for pg wire format proxying
     *
     * Generated from protobuf field <code>int32 typlen = 2;</code>
     */
    protected $typlen = 0;
    /**
     * Generated from protobuf field <code>int32 typmod = 3;</code>
     */
    protected $typmod = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type_name
     *     @type string $type_modifier
     *     @type int $oid
     *           pg object id of the type
     *           full registry could be found here: https://github.com/postgres/postgres/blob/master/src/include/catalog/pg_type.dat
     *     @type int $typlen
     *           advanced type details useful for pg wire format proxying
     *     @type int $typmod
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbValue::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string type_name = 10;</code>
     * @return string
     */
    public function getTypeName()
    {
        return $this->type_name;
    }

    /**
     * Generated from protobuf field <code>string type_name = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setTypeName($var)
    {
        GPBUtil::checkString($var, True);
        $this->type_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type_modifier = 11;</code>
     * @return string
     */
    public function getTypeModifier()
    {
        return $this->type_modifier;
    }

    /**
     * Generated from protobuf field <code>string type_modifier = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setTypeModifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->type_modifier = $var;

        return $this;
    }

    /**
     * pg object id of the type
     * full registry could be found here: https://github.com/postgres/postgres/blob/master/src/include/catalog/pg_type.dat
     *
     * Generated from protobuf field <code>uint32 oid = 1;</code>
     * @return int
     */
    public function getOid()
    {
        return $this->oid;
    }

    /**
     * pg object id of the type
     * full registry could be found here: https://github.com/postgres/postgres/blob/master/src/include/catalog/pg_type.dat
     *
     * Generated from protobuf field <code>uint32 oid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOid($var)
    {
        GPBUtil::checkUint32($var);
        $this->oid = $var;

        return $this;
    }

    /**
     * advanced type details useful for pg wire format proxying
     *
     * Generated from protobuf field <code>int32 typlen = 2;</code>
     * @return int
     */
    public function getTyplen()
    {
        return $this->typlen;
    }

    /**
     * advanced type details useful for pg wire format proxying
     *
     * Generated from protobuf field <code>int32 typlen = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTyplen($var)
    {
        GPBUtil::checkInt32($var);
        $this->typlen = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 typmod = 3;</code>
     * @return int
     */
    public function getTypmod()
    {
        return $this->typmod;
    }

    /**
     * Generated from protobuf field <code>int32 typmod = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTypmod($var)
    {
        GPBUtil::checkInt32($var);
        $this->typmod = $var;

        return $this;
    }

}

