<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_monitoring.proto

namespace Ydb\Monitoring;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Monitoring.SelfCheckRequest</code>
 */
class SelfCheckRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     */
    protected $operation_params = null;
    /**
     * Generated from protobuf field <code>bool return_verbose_status = 2;</code>
     */
    protected $return_verbose_status = false;
    /**
     * Generated from protobuf field <code>.Ydb.Monitoring.StatusFlag.Status minimum_status = 3;</code>
     */
    protected $minimum_status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ydb\Operations\OperationParams $operation_params
     *     @type bool $return_verbose_status
     *     @type int $minimum_status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kikimr\PBPublic\Api\Protos\YdbMonitoring::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     * @return \Ydb\Operations\OperationParams
     */
    public function getOperationParams()
    {
        return isset($this->operation_params) ? $this->operation_params : null;
    }

    public function hasOperationParams()
    {
        return isset($this->operation_params);
    }

    public function clearOperationParams()
    {
        unset($this->operation_params);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     * @param \Ydb\Operations\OperationParams $var
     * @return $this
     */
    public function setOperationParams($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Operations\OperationParams::class);
        $this->operation_params = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool return_verbose_status = 2;</code>
     * @return bool
     */
    public function getReturnVerboseStatus()
    {
        return $this->return_verbose_status;
    }

    /**
     * Generated from protobuf field <code>bool return_verbose_status = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setReturnVerboseStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->return_verbose_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Monitoring.StatusFlag.Status minimum_status = 3;</code>
     * @return int
     */
    public function getMinimumStatus()
    {
        return $this->minimum_status;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Monitoring.StatusFlag.Status minimum_status = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMinimumStatus($var)
    {
        GPBUtil::checkEnum($var, \Ydb\Monitoring\StatusFlag\Status::class);
        $this->minimum_status = $var;

        return $this;
    }

}

