<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_persqueue_v1.proto

namespace Ydb\PersQueue\V1\StreamingReadServerMessageNew;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.PersQueue.V1.StreamingReadServerMessageNew.AddTopicResponse</code>
 */
class AddTopicResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Block format version of data client will receive from the topic.
     *
     * Generated from protobuf field <code>int64 block_format_version = 1;</code>
     */
    protected $block_format_version = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $block_format_version
     *           Block format version of data client will receive from the topic.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kikimr\PBPublic\Api\Protos\YdbPersqueueV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Block format version of data client will receive from the topic.
     *
     * Generated from protobuf field <code>int64 block_format_version = 1;</code>
     * @return int|string
     */
    public function getBlockFormatVersion()
    {
        return $this->block_format_version;
    }

    /**
     * Block format version of data client will receive from the topic.
     *
     * Generated from protobuf field <code>int64 block_format_version = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBlockFormatVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->block_format_version = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AddTopicResponse::class, \Ydb\PersQueue\V1\StreamingReadServerMessageNew_AddTopicResponse::class);

