<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_persqueue_v1.proto

namespace Ydb\PersQueue\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.PersQueue.V1.CreateTopicRequest</code>
 */
class CreateTopicRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     */
    protected $operation_params = null;
    /**
     * Topic path.
     *
     * Generated from protobuf field <code>string path = 2 [(.Ydb.required) = true];</code>
     */
    protected $path = '';
    /**
     * Topic settings.
     *
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.TopicSettings settings = 4;</code>
     */
    protected $settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ydb\Operations\OperationParams $operation_params
     *     @type string $path
     *           Topic path.
     *     @type \Ydb\PersQueue\V1\TopicSettings $settings
     *           Topic settings.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kikimr\PBPublic\Api\Protos\YdbPersqueueV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     * @return \Ydb\Operations\OperationParams
     */
    public function getOperationParams()
    {
        return isset($this->operation_params) ? $this->operation_params : null;
    }

    public function hasOperationParams()
    {
        return isset($this->operation_params);
    }

    public function clearOperationParams()
    {
        unset($this->operation_params);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     * @param \Ydb\Operations\OperationParams $var
     * @return $this
     */
    public function setOperationParams($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Operations\OperationParams::class);
        $this->operation_params = $var;

        return $this;
    }

    /**
     * Topic path.
     *
     * Generated from protobuf field <code>string path = 2 [(.Ydb.required) = true];</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Topic path.
     *
     * Generated from protobuf field <code>string path = 2 [(.Ydb.required) = true];</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Topic settings.
     *
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.TopicSettings settings = 4;</code>
     * @return \Ydb\PersQueue\V1\TopicSettings
     */
    public function getSettings()
    {
        return isset($this->settings) ? $this->settings : null;
    }

    public function hasSettings()
    {
        return isset($this->settings);
    }

    public function clearSettings()
    {
        unset($this->settings);
    }

    /**
     * Topic settings.
     *
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.TopicSettings settings = 4;</code>
     * @param \Ydb\PersQueue\V1\TopicSettings $var
     * @return $this
     */
    public function setSettings($var)
    {
        GPBUtil::checkMessage($var, \Ydb\PersQueue\V1\TopicSettings::class);
        $this->settings = $var;

        return $this;
    }

}

