<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_persqueue_v1.proto

namespace Ydb\PersQueue\V1;

if (false) {
    /**
     * This class is deprecated. Use Ydb\PersQueue\V1\MigrationStreamingReadClientMessage\InitRequest\State instead.
     * @deprecated
     */
    class MigrationStreamingReadClientMessage_InitRequest_State {}
}
class_exists(MigrationStreamingReadClientMessage\InitRequest\State::class);
@trigger_error('Ydb\PersQueue\V1\MigrationStreamingReadClientMessage_InitRequest_State is deprecated and will be removed in the next major release. Use Ydb\PersQueue\V1\MigrationStreamingReadClientMessage\InitRequest\State instead', E_USER_DEPRECATED);

