<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_persqueue_v1.proto

namespace Ydb\PersQueue\V1;

if (false) {
    /**
     * This class is deprecated. Use Ydb\PersQueue\V1\MigrationStreamingReadClientMessage\TopicReadSettings instead.
     * @deprecated
     */
    class MigrationStreamingReadClientMessage_TopicReadSettings {}
}
class_exists(MigrationStreamingReadClientMessage\TopicReadSettings::class);
@trigger_error('Ydb\PersQueue\V1\MigrationStreamingReadClientMessage_TopicReadSettings is deprecated and will be removed in the next major release. Use Ydb\PersQueue\V1\MigrationStreamingReadClientMessage\TopicReadSettings instead', E_USER_DEPRECATED);

