<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_persqueue_v1.proto

namespace Ydb\PersQueue\V1;

if (false) {
    /**
     * This class is deprecated. Use Ydb\PersQueue\V1\MigrationStreamingReadClientMessage\StartRead instead.
     * @deprecated
     */
    class MigrationStreamingReadClientMessage_StartRead {}
}
class_exists(MigrationStreamingReadClientMessage\StartRead::class);
@trigger_error('Ydb\PersQueue\V1\MigrationStreamingReadClientMessage_StartRead is deprecated and will be removed in the next major release. Use Ydb\PersQueue\V1\MigrationStreamingReadClientMessage\StartRead instead', E_USER_DEPRECATED);

