<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_persqueue_v1.proto

namespace Ydb\PersQueue\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * Single read parameters for server.
 *
 * Generated from protobuf message <code>Ydb.PersQueue.V1.ReadParams</code>
 */
class ReadParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Max messages to give to client in one read request.
     *
     * Generated from protobuf field <code>uint32 max_read_messages_count = 1;</code>
     */
    protected $max_read_messages_count = 0;
    /**
     * Max size in bytes to give to client in one read request.
     *
     * Generated from protobuf field <code>uint32 max_read_size = 2;</code>
     */
    protected $max_read_size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $max_read_messages_count
     *           Max messages to give to client in one read request.
     *     @type int $max_read_size
     *           Max size in bytes to give to client in one read request.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kikimr\PBPublic\Api\Protos\YdbPersqueueV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Max messages to give to client in one read request.
     *
     * Generated from protobuf field <code>uint32 max_read_messages_count = 1;</code>
     * @return int
     */
    public function getMaxReadMessagesCount()
    {
        return $this->max_read_messages_count;
    }

    /**
     * Max messages to give to client in one read request.
     *
     * Generated from protobuf field <code>uint32 max_read_messages_count = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxReadMessagesCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_read_messages_count = $var;

        return $this;
    }

    /**
     * Max size in bytes to give to client in one read request.
     *
     * Generated from protobuf field <code>uint32 max_read_size = 2;</code>
     * @return int
     */
    public function getMaxReadSize()
    {
        return $this->max_read_size;
    }

    /**
     * Max size in bytes to give to client in one read request.
     *
     * Generated from protobuf field <code>uint32 max_read_size = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxReadSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_read_size = $var;

        return $this;
    }

}

