<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_persqueue_v1.proto

namespace Ydb\PersQueue\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.PersQueue.V1.ReadInfoResult</code>
 */
class ReadInfoResult extends \Google\Protobuf\Internal\Message
{
    /**
     * List of topics info.
     *
     * Generated from protobuf field <code>repeated .Ydb.PersQueue.V1.ReadInfoResult.TopicInfo topics = 1;</code>
     */
    private $topics;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ydb\PersQueue\V1\ReadInfoResult\TopicInfo[]|\Google\Protobuf\Internal\RepeatedField $topics
     *           List of topics info.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kikimr\PBPublic\Api\Protos\YdbPersqueueV1::initOnce();
        parent::__construct($data);
    }

    /**
     * List of topics info.
     *
     * Generated from protobuf field <code>repeated .Ydb.PersQueue.V1.ReadInfoResult.TopicInfo topics = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTopics()
    {
        return $this->topics;
    }

    /**
     * List of topics info.
     *
     * Generated from protobuf field <code>repeated .Ydb.PersQueue.V1.ReadInfoResult.TopicInfo topics = 1;</code>
     * @param \Ydb\PersQueue\V1\ReadInfoResult\TopicInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTopics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ydb\PersQueue\V1\ReadInfoResult\TopicInfo::class);
        $this->topics = $arr;

        return $this;
    }

}

