<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_persqueue_v1.proto

namespace Ydb\PersQueue\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * Request for read session. Contains one of:
 *      InitRequest - handshake request.
 *      ReadRequest - request for data.
 *      CommitRequest - request for commit of some read data.
 *      CreatePartitionStreamResponse - signal for server that client is ready to get data from partition.
 *      DestroyPartitionStreamResponse - signal for server that client finished working with partition. Must be sent only after corresponding Release request from server.
 *      StopReadRequest - signal for server that client is not ready to get more data from this partition.
 *      ResumeReadRequest - signal for server that client is ready to get more data from this partition.
 *
 * Generated from protobuf message <code>Ydb.PersQueue.V1.StreamingReadClientMessageNew</code>
 */
class StreamingReadClientMessageNew extends \Google\Protobuf\Internal\Message
{
    /**
     * User credentials if update is needed or empty string.
     *
     * Generated from protobuf field <code>string token = 20;</code>
     */
    protected $token = '';
    protected $client_message;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ydb\PersQueue\V1\StreamingReadClientMessageNew\InitRequest $init_request
     *     @type \Ydb\PersQueue\V1\StreamingReadClientMessageNew\ReadRequest $read_request
     *     @type \Ydb\PersQueue\V1\StreamingReadClientMessageNew\CreatePartitionStreamResponse $create_partition_stream_response
     *     @type \Ydb\PersQueue\V1\StreamingReadClientMessageNew\CommitRequest $commit_request
     *     @type \Ydb\PersQueue\V1\StreamingReadClientMessageNew\DestroyPartitionStreamResponse $destroy_partition_stream_response
     *     @type \Ydb\PersQueue\V1\StreamingReadClientMessageNew\StopReadRequest $stop_read_request
     *     @type \Ydb\PersQueue\V1\StreamingReadClientMessageNew\ResumeReadRequest $resume_read_request
     *     @type \Ydb\PersQueue\V1\StreamingReadClientMessageNew\PartitionStreamStatusRequest $partition_stream_status_request
     *     @type \Ydb\PersQueue\V1\StreamingReadClientMessageNew\AddTopicRequest $add_topic_request
     *     @type \Ydb\PersQueue\V1\StreamingReadClientMessageNew\RemoveTopicRequest $remove_topic_request
     *     @type string $token
     *           User credentials if update is needed or empty string.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kikimr\PBPublic\Api\Protos\YdbPersqueueV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.InitRequest init_request = 1;</code>
     * @return \Ydb\PersQueue\V1\StreamingReadClientMessageNew\InitRequest
     */
    public function getInitRequest()
    {
        return $this->readOneof(1);
    }

    public function hasInitRequest()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.InitRequest init_request = 1;</code>
     * @param \Ydb\PersQueue\V1\StreamingReadClientMessageNew\InitRequest $var
     * @return $this
     */
    public function setInitRequest($var)
    {
        GPBUtil::checkMessage($var, \Ydb\PersQueue\V1\StreamingReadClientMessageNew\InitRequest::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.ReadRequest read_request = 2;</code>
     * @return \Ydb\PersQueue\V1\StreamingReadClientMessageNew\ReadRequest
     */
    public function getReadRequest()
    {
        return $this->readOneof(2);
    }

    public function hasReadRequest()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.ReadRequest read_request = 2;</code>
     * @param \Ydb\PersQueue\V1\StreamingReadClientMessageNew\ReadRequest $var
     * @return $this
     */
    public function setReadRequest($var)
    {
        GPBUtil::checkMessage($var, \Ydb\PersQueue\V1\StreamingReadClientMessageNew\ReadRequest::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.CreatePartitionStreamResponse create_partition_stream_response = 3;</code>
     * @return \Ydb\PersQueue\V1\StreamingReadClientMessageNew\CreatePartitionStreamResponse
     */
    public function getCreatePartitionStreamResponse()
    {
        return $this->readOneof(3);
    }

    public function hasCreatePartitionStreamResponse()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.CreatePartitionStreamResponse create_partition_stream_response = 3;</code>
     * @param \Ydb\PersQueue\V1\StreamingReadClientMessageNew\CreatePartitionStreamResponse $var
     * @return $this
     */
    public function setCreatePartitionStreamResponse($var)
    {
        GPBUtil::checkMessage($var, \Ydb\PersQueue\V1\StreamingReadClientMessageNew\CreatePartitionStreamResponse::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.CommitRequest commit_request = 4;</code>
     * @return \Ydb\PersQueue\V1\StreamingReadClientMessageNew\CommitRequest
     */
    public function getCommitRequest()
    {
        return $this->readOneof(4);
    }

    public function hasCommitRequest()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.CommitRequest commit_request = 4;</code>
     * @param \Ydb\PersQueue\V1\StreamingReadClientMessageNew\CommitRequest $var
     * @return $this
     */
    public function setCommitRequest($var)
    {
        GPBUtil::checkMessage($var, \Ydb\PersQueue\V1\StreamingReadClientMessageNew\CommitRequest::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.DestroyPartitionStreamResponse destroy_partition_stream_response = 5;</code>
     * @return \Ydb\PersQueue\V1\StreamingReadClientMessageNew\DestroyPartitionStreamResponse
     */
    public function getDestroyPartitionStreamResponse()
    {
        return $this->readOneof(5);
    }

    public function hasDestroyPartitionStreamResponse()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.DestroyPartitionStreamResponse destroy_partition_stream_response = 5;</code>
     * @param \Ydb\PersQueue\V1\StreamingReadClientMessageNew\DestroyPartitionStreamResponse $var
     * @return $this
     */
    public function setDestroyPartitionStreamResponse($var)
    {
        GPBUtil::checkMessage($var, \Ydb\PersQueue\V1\StreamingReadClientMessageNew\DestroyPartitionStreamResponse::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.StopReadRequest stop_read_request = 6;</code>
     * @return \Ydb\PersQueue\V1\StreamingReadClientMessageNew\StopReadRequest
     */
    public function getStopReadRequest()
    {
        return $this->readOneof(6);
    }

    public function hasStopReadRequest()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.StopReadRequest stop_read_request = 6;</code>
     * @param \Ydb\PersQueue\V1\StreamingReadClientMessageNew\StopReadRequest $var
     * @return $this
     */
    public function setStopReadRequest($var)
    {
        GPBUtil::checkMessage($var, \Ydb\PersQueue\V1\StreamingReadClientMessageNew\StopReadRequest::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.ResumeReadRequest resume_read_request = 7;</code>
     * @return \Ydb\PersQueue\V1\StreamingReadClientMessageNew\ResumeReadRequest
     */
    public function getResumeReadRequest()
    {
        return $this->readOneof(7);
    }

    public function hasResumeReadRequest()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.ResumeReadRequest resume_read_request = 7;</code>
     * @param \Ydb\PersQueue\V1\StreamingReadClientMessageNew\ResumeReadRequest $var
     * @return $this
     */
    public function setResumeReadRequest($var)
    {
        GPBUtil::checkMessage($var, \Ydb\PersQueue\V1\StreamingReadClientMessageNew\ResumeReadRequest::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.PartitionStreamStatusRequest partition_stream_status_request = 8;</code>
     * @return \Ydb\PersQueue\V1\StreamingReadClientMessageNew\PartitionStreamStatusRequest
     */
    public function getPartitionStreamStatusRequest()
    {
        return $this->readOneof(8);
    }

    public function hasPartitionStreamStatusRequest()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.PartitionStreamStatusRequest partition_stream_status_request = 8;</code>
     * @param \Ydb\PersQueue\V1\StreamingReadClientMessageNew\PartitionStreamStatusRequest $var
     * @return $this
     */
    public function setPartitionStreamStatusRequest($var)
    {
        GPBUtil::checkMessage($var, \Ydb\PersQueue\V1\StreamingReadClientMessageNew\PartitionStreamStatusRequest::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.AddTopicRequest add_topic_request = 9;</code>
     * @return \Ydb\PersQueue\V1\StreamingReadClientMessageNew\AddTopicRequest
     */
    public function getAddTopicRequest()
    {
        return $this->readOneof(9);
    }

    public function hasAddTopicRequest()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.AddTopicRequest add_topic_request = 9;</code>
     * @param \Ydb\PersQueue\V1\StreamingReadClientMessageNew\AddTopicRequest $var
     * @return $this
     */
    public function setAddTopicRequest($var)
    {
        GPBUtil::checkMessage($var, \Ydb\PersQueue\V1\StreamingReadClientMessageNew\AddTopicRequest::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.RemoveTopicRequest remove_topic_request = 10;</code>
     * @return \Ydb\PersQueue\V1\StreamingReadClientMessageNew\RemoveTopicRequest
     */
    public function getRemoveTopicRequest()
    {
        return $this->readOneof(10);
    }

    public function hasRemoveTopicRequest()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>.Ydb.PersQueue.V1.StreamingReadClientMessageNew.RemoveTopicRequest remove_topic_request = 10;</code>
     * @param \Ydb\PersQueue\V1\StreamingReadClientMessageNew\RemoveTopicRequest $var
     * @return $this
     */
    public function setRemoveTopicRequest($var)
    {
        GPBUtil::checkMessage($var, \Ydb\PersQueue\V1\StreamingReadClientMessageNew\RemoveTopicRequest::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * User credentials if update is needed or empty string.
     *
     * Generated from protobuf field <code>string token = 20;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * User credentials if update is needed or empty string.
     *
     * Generated from protobuf field <code>string token = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getClientMessage()
    {
        return $this->whichOneof("client_message");
    }

}

