<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_persqueue_v1.proto

namespace Ydb\PersQueue\V1;

if (false) {
    /**
     * This class is deprecated. Use Ydb\PersQueue\V1\StreamingReadServerMessageNew\RemoveTopicResponse instead.
     * @deprecated
     */
    class StreamingReadServerMessageNew_RemoveTopicResponse {}
}
class_exists(StreamingReadServerMessageNew\RemoveTopicResponse::class);
@trigger_error('Ydb\PersQueue\V1\StreamingReadServerMessageNew_RemoveTopicResponse is deprecated and will be removed in the next major release. Use Ydb\PersQueue\V1\StreamingReadServerMessageNew\RemoveTopicResponse instead', E_USER_DEPRECATED);

