<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_persqueue_v1.proto

namespace Ydb\PersQueue\V1;

if (false) {
    /**
     * This class is deprecated. Use Ydb\PersQueue\V1\StreamingReadClientMessageNew\PartitionStreamStatusRequest instead.
     * @deprecated
     */
    class StreamingReadClientMessageNew_PartitionStreamStatusRequest {}
}
class_exists(StreamingReadClientMessageNew\PartitionStreamStatusRequest::class);
@trigger_error('Ydb\PersQueue\V1\StreamingReadClientMessageNew_PartitionStreamStatusRequest is deprecated and will be removed in the next major release. Use Ydb\PersQueue\V1\StreamingReadClientMessageNew\PartitionStreamStatusRequest instead', E_USER_DEPRECATED);

