<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_topic.proto

namespace Ydb\Topic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Topic.AlterAutoPartitioningSettings</code>
 */
class AlterAutoPartitioningSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Strategy of auto partitioning
     *
     * Generated from protobuf field <code>optional .Ydb.Topic.AutoPartitioningStrategy set_strategy = 1;</code>
     */
    protected $set_strategy = null;
    /**
     * Auto partitioning write speed options.
     *
     * Generated from protobuf field <code>optional .Ydb.Topic.AlterAutoPartitioningWriteSpeedStrategy set_partition_write_speed = 2;</code>
     */
    protected $set_partition_write_speed = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $set_strategy
     *           Strategy of auto partitioning
     *     @type \Ydb\Topic\AlterAutoPartitioningWriteSpeedStrategy $set_partition_write_speed
     *           Auto partitioning write speed options.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTopic::initOnce();
        parent::__construct($data);
    }

    /**
     * Strategy of auto partitioning
     *
     * Generated from protobuf field <code>optional .Ydb.Topic.AutoPartitioningStrategy set_strategy = 1;</code>
     * @return int
     */
    public function getSetStrategy()
    {
        return isset($this->set_strategy) ? $this->set_strategy : 0;
    }

    public function hasSetStrategy()
    {
        return isset($this->set_strategy);
    }

    public function clearSetStrategy()
    {
        unset($this->set_strategy);
    }

    /**
     * Strategy of auto partitioning
     *
     * Generated from protobuf field <code>optional .Ydb.Topic.AutoPartitioningStrategy set_strategy = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSetStrategy($var)
    {
        GPBUtil::checkEnum($var, \Ydb\Topic\AutoPartitioningStrategy::class);
        $this->set_strategy = $var;

        return $this;
    }

    /**
     * Auto partitioning write speed options.
     *
     * Generated from protobuf field <code>optional .Ydb.Topic.AlterAutoPartitioningWriteSpeedStrategy set_partition_write_speed = 2;</code>
     * @return \Ydb\Topic\AlterAutoPartitioningWriteSpeedStrategy|null
     */
    public function getSetPartitionWriteSpeed()
    {
        return $this->set_partition_write_speed;
    }

    public function hasSetPartitionWriteSpeed()
    {
        return isset($this->set_partition_write_speed);
    }

    public function clearSetPartitionWriteSpeed()
    {
        unset($this->set_partition_write_speed);
    }

    /**
     * Auto partitioning write speed options.
     *
     * Generated from protobuf field <code>optional .Ydb.Topic.AlterAutoPartitioningWriteSpeedStrategy set_partition_write_speed = 2;</code>
     * @param \Ydb\Topic\AlterAutoPartitioningWriteSpeedStrategy $var
     * @return $this
     */
    public function setSetPartitionWriteSpeed($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Topic\AlterAutoPartitioningWriteSpeedStrategy::class);
        $this->set_partition_write_speed = $var;

        return $this;
    }

}

