<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_topic.proto

namespace Ydb\Topic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Topic.AlterAutoPartitioningWriteSpeedStrategy</code>
 */
class AlterAutoPartitioningWriteSpeedStrategy extends \Google\Protobuf\Internal\Message
{
    /**
     * The time of exceeding the threshold value, after which the partition will be
     * auto partitioning.
     * Zero value means default - 300.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Duration set_stabilization_window = 1;</code>
     */
    protected $set_stabilization_window = null;
    /**
     * The threshold value of the write speed to the partition as a percentage, when exceeded,
     * the partition will be auto split.
     * Zero value means default - 90.
     *
     * Generated from protobuf field <code>optional int32 set_up_utilization_percent = 2 [(.Ydb.value) = ">= 0"];</code>
     */
    protected $set_up_utilization_percent = null;
    /**
     * The threshold value of the write speed to the partition as a percentage, if it is not reached,
     * the partition will be auto merged.
     * Zero value means default - 30.
     *
     * Generated from protobuf field <code>optional int32 set_down_utilization_percent = 3 [(.Ydb.value) = ">= 0"];</code>
     */
    protected $set_down_utilization_percent = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Duration $set_stabilization_window
     *           The time of exceeding the threshold value, after which the partition will be
     *           auto partitioning.
     *           Zero value means default - 300.
     *     @type int $set_up_utilization_percent
     *           The threshold value of the write speed to the partition as a percentage, when exceeded,
     *           the partition will be auto split.
     *           Zero value means default - 90.
     *     @type int $set_down_utilization_percent
     *           The threshold value of the write speed to the partition as a percentage, if it is not reached,
     *           the partition will be auto merged.
     *           Zero value means default - 30.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTopic::initOnce();
        parent::__construct($data);
    }

    /**
     * The time of exceeding the threshold value, after which the partition will be
     * auto partitioning.
     * Zero value means default - 300.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Duration set_stabilization_window = 1;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getSetStabilizationWindow()
    {
        return $this->set_stabilization_window;
    }

    public function hasSetStabilizationWindow()
    {
        return isset($this->set_stabilization_window);
    }

    public function clearSetStabilizationWindow()
    {
        unset($this->set_stabilization_window);
    }

    /**
     * The time of exceeding the threshold value, after which the partition will be
     * auto partitioning.
     * Zero value means default - 300.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Duration set_stabilization_window = 1;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setSetStabilizationWindow($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->set_stabilization_window = $var;

        return $this;
    }

    /**
     * The threshold value of the write speed to the partition as a percentage, when exceeded,
     * the partition will be auto split.
     * Zero value means default - 90.
     *
     * Generated from protobuf field <code>optional int32 set_up_utilization_percent = 2 [(.Ydb.value) = ">= 0"];</code>
     * @return int
     */
    public function getSetUpUtilizationPercent()
    {
        return isset($this->set_up_utilization_percent) ? $this->set_up_utilization_percent : 0;
    }

    public function hasSetUpUtilizationPercent()
    {
        return isset($this->set_up_utilization_percent);
    }

    public function clearSetUpUtilizationPercent()
    {
        unset($this->set_up_utilization_percent);
    }

    /**
     * The threshold value of the write speed to the partition as a percentage, when exceeded,
     * the partition will be auto split.
     * Zero value means default - 90.
     *
     * Generated from protobuf field <code>optional int32 set_up_utilization_percent = 2 [(.Ydb.value) = ">= 0"];</code>
     * @param int $var
     * @return $this
     */
    public function setSetUpUtilizationPercent($var)
    {
        GPBUtil::checkInt32($var);
        $this->set_up_utilization_percent = $var;

        return $this;
    }

    /**
     * The threshold value of the write speed to the partition as a percentage, if it is not reached,
     * the partition will be auto merged.
     * Zero value means default - 30.
     *
     * Generated from protobuf field <code>optional int32 set_down_utilization_percent = 3 [(.Ydb.value) = ">= 0"];</code>
     * @return int
     */
    public function getSetDownUtilizationPercent()
    {
        return isset($this->set_down_utilization_percent) ? $this->set_down_utilization_percent : 0;
    }

    public function hasSetDownUtilizationPercent()
    {
        return isset($this->set_down_utilization_percent);
    }

    public function clearSetDownUtilizationPercent()
    {
        unset($this->set_down_utilization_percent);
    }

    /**
     * The threshold value of the write speed to the partition as a percentage, if it is not reached,
     * the partition will be auto merged.
     * Zero value means default - 30.
     *
     * Generated from protobuf field <code>optional int32 set_down_utilization_percent = 3 [(.Ydb.value) = ">= 0"];</code>
     * @param int $var
     * @return $this
     */
    public function setSetDownUtilizationPercent($var)
    {
        GPBUtil::checkInt32($var);
        $this->set_down_utilization_percent = $var;

        return $this;
    }

}

