<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_topic.proto

namespace Ydb\Topic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Partition will be auto partitioned up (divided into 2 partitions)
 *after write speed to the partition exceeds up_utilization_percent (in percentage of maximum write speed to the partition) for the period of time stabilization_window
 *
 * Generated from protobuf message <code>Ydb.Topic.AutoPartitioningWriteSpeedStrategy</code>
 */
class AutoPartitioningWriteSpeedStrategy extends \Google\Protobuf\Internal\Message
{
    /**
     * Zero value means default - 300.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration stabilization_window = 1;</code>
     */
    protected $stabilization_window = null;
    /**
     * Zero value means default - 90.
     *
     * Generated from protobuf field <code>int32 up_utilization_percent = 2 [(.Ydb.value) = ">= 0"];</code>
     */
    protected $up_utilization_percent = 0;
    /**
     * Zero value means default - 30.
     *
     * Generated from protobuf field <code>int32 down_utilization_percent = 3 [(.Ydb.value) = ">= 0"];</code>
     */
    protected $down_utilization_percent = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Duration $stabilization_window
     *           Zero value means default - 300.
     *     @type int $up_utilization_percent
     *           Zero value means default - 90.
     *     @type int $down_utilization_percent
     *           Zero value means default - 30.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTopic::initOnce();
        parent::__construct($data);
    }

    /**
     * Zero value means default - 300.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration stabilization_window = 1;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getStabilizationWindow()
    {
        return $this->stabilization_window;
    }

    public function hasStabilizationWindow()
    {
        return isset($this->stabilization_window);
    }

    public function clearStabilizationWindow()
    {
        unset($this->stabilization_window);
    }

    /**
     * Zero value means default - 300.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration stabilization_window = 1;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setStabilizationWindow($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->stabilization_window = $var;

        return $this;
    }

    /**
     * Zero value means default - 90.
     *
     * Generated from protobuf field <code>int32 up_utilization_percent = 2 [(.Ydb.value) = ">= 0"];</code>
     * @return int
     */
    public function getUpUtilizationPercent()
    {
        return $this->up_utilization_percent;
    }

    /**
     * Zero value means default - 90.
     *
     * Generated from protobuf field <code>int32 up_utilization_percent = 2 [(.Ydb.value) = ">= 0"];</code>
     * @param int $var
     * @return $this
     */
    public function setUpUtilizationPercent($var)
    {
        GPBUtil::checkInt32($var);
        $this->up_utilization_percent = $var;

        return $this;
    }

    /**
     * Zero value means default - 30.
     *
     * Generated from protobuf field <code>int32 down_utilization_percent = 3 [(.Ydb.value) = ">= 0"];</code>
     * @return int
     */
    public function getDownUtilizationPercent()
    {
        return $this->down_utilization_percent;
    }

    /**
     * Zero value means default - 30.
     *
     * Generated from protobuf field <code>int32 down_utilization_percent = 3 [(.Ydb.value) = ">= 0"];</code>
     * @param int $var
     * @return $this
     */
    public function setDownUtilizationPercent($var)
    {
        GPBUtil::checkInt32($var);
        $this->down_utilization_percent = $var;

        return $this;
    }

}

