<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_topic.proto

namespace Ydb\Topic;

use UnexpectedValueException;

/**
 * Protobuf type <code>Ydb.Topic.AutoPartitioningStrategy</code>
 */
class AutoPartitioningStrategy
{
    /**
     * The auto partitioning algorithm is not specified. The default value will be used.
     *
     * Generated from protobuf enum <code>AUTO_PARTITIONING_STRATEGY_UNSPECIFIED = 0;</code>
     */
    const AUTO_PARTITIONING_STRATEGY_UNSPECIFIED = 0;
    /**
     * The auto partitioning is disabled.
     *
     * Generated from protobuf enum <code>AUTO_PARTITIONING_STRATEGY_DISABLED = 1;</code>
     */
    const AUTO_PARTITIONING_STRATEGY_DISABLED = 1;
    /**
     * The auto partitioning algorithm will increase partitions count depending on the load characteristics.
     * The auto partitioning algorithm will never decrease the number of partitions.
     *
     * Generated from protobuf enum <code>AUTO_PARTITIONING_STRATEGY_SCALE_UP = 2;</code>
     */
    const AUTO_PARTITIONING_STRATEGY_SCALE_UP = 2;
    /**
     * The auto partitioning algorithm will both increase and decrease partitions count depending on the load characteristics.
     *
     * Generated from protobuf enum <code>AUTO_PARTITIONING_STRATEGY_SCALE_UP_AND_DOWN = 3;</code>
     */
    const AUTO_PARTITIONING_STRATEGY_SCALE_UP_AND_DOWN = 3;
    /**
     * The auto partitioning is paused.
     *
     * Generated from protobuf enum <code>AUTO_PARTITIONING_STRATEGY_PAUSED = 4;</code>
     */
    const AUTO_PARTITIONING_STRATEGY_PAUSED = 4;

    private static $valueToName = [
        self::AUTO_PARTITIONING_STRATEGY_UNSPECIFIED => 'AUTO_PARTITIONING_STRATEGY_UNSPECIFIED',
        self::AUTO_PARTITIONING_STRATEGY_DISABLED => 'AUTO_PARTITIONING_STRATEGY_DISABLED',
        self::AUTO_PARTITIONING_STRATEGY_SCALE_UP => 'AUTO_PARTITIONING_STRATEGY_SCALE_UP',
        self::AUTO_PARTITIONING_STRATEGY_SCALE_UP_AND_DOWN => 'AUTO_PARTITIONING_STRATEGY_SCALE_UP_AND_DOWN',
        self::AUTO_PARTITIONING_STRATEGY_PAUSED => 'AUTO_PARTITIONING_STRATEGY_PAUSED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

