<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_topic.proto

namespace Ydb\Topic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Topic.AutoPartitioningSettings</code>
 */
class AutoPartitioningSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Strategy of auto partitioning.
     *
     * Generated from protobuf field <code>.Ydb.Topic.AutoPartitioningStrategy strategy = 1;</code>
     */
    protected $strategy = 0;
    /**
     * Partition write speed auto partitioning options.
     *
     * Generated from protobuf field <code>.Ydb.Topic.AutoPartitioningWriteSpeedStrategy partition_write_speed = 2;</code>
     */
    protected $partition_write_speed = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $strategy
     *           Strategy of auto partitioning.
     *     @type \Ydb\Topic\AutoPartitioningWriteSpeedStrategy $partition_write_speed
     *           Partition write speed auto partitioning options.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTopic::initOnce();
        parent::__construct($data);
    }

    /**
     * Strategy of auto partitioning.
     *
     * Generated from protobuf field <code>.Ydb.Topic.AutoPartitioningStrategy strategy = 1;</code>
     * @return int
     */
    public function getStrategy()
    {
        return $this->strategy;
    }

    /**
     * Strategy of auto partitioning.
     *
     * Generated from protobuf field <code>.Ydb.Topic.AutoPartitioningStrategy strategy = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStrategy($var)
    {
        GPBUtil::checkEnum($var, \Ydb\Topic\AutoPartitioningStrategy::class);
        $this->strategy = $var;

        return $this;
    }

    /**
     * Partition write speed auto partitioning options.
     *
     * Generated from protobuf field <code>.Ydb.Topic.AutoPartitioningWriteSpeedStrategy partition_write_speed = 2;</code>
     * @return \Ydb\Topic\AutoPartitioningWriteSpeedStrategy|null
     */
    public function getPartitionWriteSpeed()
    {
        return $this->partition_write_speed;
    }

    public function hasPartitionWriteSpeed()
    {
        return isset($this->partition_write_speed);
    }

    public function clearPartitionWriteSpeed()
    {
        unset($this->partition_write_speed);
    }

    /**
     * Partition write speed auto partitioning options.
     *
     * Generated from protobuf field <code>.Ydb.Topic.AutoPartitioningWriteSpeedStrategy partition_write_speed = 2;</code>
     * @param \Ydb\Topic\AutoPartitioningWriteSpeedStrategy $var
     * @return $this
     */
    public function setPartitionWriteSpeed($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Topic\AutoPartitioningWriteSpeedStrategy::class);
        $this->partition_write_speed = $var;

        return $this;
    }

}

