<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_topic.proto

namespace Ydb\Topic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describe partition request sent from client to server.
 *
 * Generated from protobuf message <code>Ydb.Topic.DescribePartitionRequest</code>
 */
class DescribePartitionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     */
    protected $operation_params = null;
    /**
     * Topic path.
     *
     * Generated from protobuf field <code>string path = 2;</code>
     */
    protected $path = '';
    /**
     * Partition identifier.
     *
     * Generated from protobuf field <code>int64 partition_id = 3;</code>
     */
    protected $partition_id = 0;
    /**
     * Include partition statistics.
     *
     * Generated from protobuf field <code>bool include_stats = 4;</code>
     */
    protected $include_stats = false;
    /**
     * Include partition location.
     *
     * Generated from protobuf field <code>bool include_location = 5;</code>
     */
    protected $include_location = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ydb\Operations\OperationParams $operation_params
     *     @type string $path
     *           Topic path.
     *     @type int|string $partition_id
     *           Partition identifier.
     *     @type bool $include_stats
     *           Include partition statistics.
     *     @type bool $include_location
     *           Include partition location.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTopic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     * @return \Ydb\Operations\OperationParams|null
     */
    public function getOperationParams()
    {
        return $this->operation_params;
    }

    public function hasOperationParams()
    {
        return isset($this->operation_params);
    }

    public function clearOperationParams()
    {
        unset($this->operation_params);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     * @param \Ydb\Operations\OperationParams $var
     * @return $this
     */
    public function setOperationParams($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Operations\OperationParams::class);
        $this->operation_params = $var;

        return $this;
    }

    /**
     * Topic path.
     *
     * Generated from protobuf field <code>string path = 2;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Topic path.
     *
     * Generated from protobuf field <code>string path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Partition identifier.
     *
     * Generated from protobuf field <code>int64 partition_id = 3;</code>
     * @return int|string
     */
    public function getPartitionId()
    {
        return $this->partition_id;
    }

    /**
     * Partition identifier.
     *
     * Generated from protobuf field <code>int64 partition_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPartitionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->partition_id = $var;

        return $this;
    }

    /**
     * Include partition statistics.
     *
     * Generated from protobuf field <code>bool include_stats = 4;</code>
     * @return bool
     */
    public function getIncludeStats()
    {
        return $this->include_stats;
    }

    /**
     * Include partition statistics.
     *
     * Generated from protobuf field <code>bool include_stats = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeStats($var)
    {
        GPBUtil::checkBool($var);
        $this->include_stats = $var;

        return $this;
    }

    /**
     * Include partition location.
     *
     * Generated from protobuf field <code>bool include_location = 5;</code>
     * @return bool
     */
    public function getIncludeLocation()
    {
        return $this->include_location;
    }

    /**
     * Include partition location.
     *
     * Generated from protobuf field <code>bool include_location = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeLocation($var)
    {
        GPBUtil::checkBool($var);
        $this->include_location = $var;

        return $this;
    }

}

