<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_topic.proto

namespace Ydb\Topic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Partitioning settings for topic.
 *
 * Generated from protobuf message <code>Ydb.Topic.PartitioningSettings</code>
 */
class PartitioningSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Minimum partition count auto merge would stop working at.
     * Zero value means default - 1.
     *
     * Generated from protobuf field <code>int64 min_active_partitions = 1 [(.Ydb.value) = ">= 0"];</code>
     */
    protected $min_active_partitions = 0;
    /**
     * Limit for total partition count, including active (open for write) and read-only partitions.
     * Zero value means default - 100.
     *
     * Generated from protobuf field <code>int64 partition_count_limit = 2 [(.Ydb.value) = ">= 0"];</code>
     */
    protected $partition_count_limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $min_active_partitions
     *           Minimum partition count auto merge would stop working at.
     *           Zero value means default - 1.
     *     @type int|string $partition_count_limit
     *           Limit for total partition count, including active (open for write) and read-only partitions.
     *           Zero value means default - 100.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTopic::initOnce();
        parent::__construct($data);
    }

    /**
     * Minimum partition count auto merge would stop working at.
     * Zero value means default - 1.
     *
     * Generated from protobuf field <code>int64 min_active_partitions = 1 [(.Ydb.value) = ">= 0"];</code>
     * @return int|string
     */
    public function getMinActivePartitions()
    {
        return $this->min_active_partitions;
    }

    /**
     * Minimum partition count auto merge would stop working at.
     * Zero value means default - 1.
     *
     * Generated from protobuf field <code>int64 min_active_partitions = 1 [(.Ydb.value) = ">= 0"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinActivePartitions($var)
    {
        GPBUtil::checkInt64($var);
        $this->min_active_partitions = $var;

        return $this;
    }

    /**
     * Limit for total partition count, including active (open for write) and read-only partitions.
     * Zero value means default - 100.
     *
     * Generated from protobuf field <code>int64 partition_count_limit = 2 [(.Ydb.value) = ">= 0"];</code>
     * @return int|string
     */
    public function getPartitionCountLimit()
    {
        return $this->partition_count_limit;
    }

    /**
     * Limit for total partition count, including active (open for write) and read-only partitions.
     * Zero value means default - 100.
     *
     * Generated from protobuf field <code>int64 partition_count_limit = 2 [(.Ydb.value) = ">= 0"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setPartitionCountLimit($var)
    {
        GPBUtil::checkInt64($var);
        $this->partition_count_limit = $var;

        return $this;
    }

}

