<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_topic.proto

namespace Ydb\Topic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Add offsets to transaction request sent from client to server.
 *
 * Generated from protobuf message <code>Ydb.Topic.UpdateOffsetsInTransactionRequest</code>
 */
class UpdateOffsetsInTransactionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     */
    protected $operation_params = null;
    /**
     * Generated from protobuf field <code>.Ydb.Topic.TransactionIdentity tx = 2;</code>
     */
    protected $tx = null;
    /**
     * Ranges of offsets by topics.
     *
     * Generated from protobuf field <code>repeated .Ydb.Topic.UpdateOffsetsInTransactionRequest.TopicOffsets topics = 3;</code>
     */
    private $topics;
    /**
     * Generated from protobuf field <code>string consumer = 4;</code>
     */
    protected $consumer = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ydb\Operations\OperationParams $operation_params
     *     @type \Ydb\Topic\TransactionIdentity $tx
     *     @type array<\Ydb\Topic\UpdateOffsetsInTransactionRequest\TopicOffsets>|\Google\Protobuf\Internal\RepeatedField $topics
     *           Ranges of offsets by topics.
     *     @type string $consumer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTopic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     * @return \Ydb\Operations\OperationParams|null
     */
    public function getOperationParams()
    {
        return $this->operation_params;
    }

    public function hasOperationParams()
    {
        return isset($this->operation_params);
    }

    public function clearOperationParams()
    {
        unset($this->operation_params);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     * @param \Ydb\Operations\OperationParams $var
     * @return $this
     */
    public function setOperationParams($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Operations\OperationParams::class);
        $this->operation_params = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Topic.TransactionIdentity tx = 2;</code>
     * @return \Ydb\Topic\TransactionIdentity|null
     */
    public function getTx()
    {
        return $this->tx;
    }

    public function hasTx()
    {
        return isset($this->tx);
    }

    public function clearTx()
    {
        unset($this->tx);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Topic.TransactionIdentity tx = 2;</code>
     * @param \Ydb\Topic\TransactionIdentity $var
     * @return $this
     */
    public function setTx($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Topic\TransactionIdentity::class);
        $this->tx = $var;

        return $this;
    }

    /**
     * Ranges of offsets by topics.
     *
     * Generated from protobuf field <code>repeated .Ydb.Topic.UpdateOffsetsInTransactionRequest.TopicOffsets topics = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTopics()
    {
        return $this->topics;
    }

    /**
     * Ranges of offsets by topics.
     *
     * Generated from protobuf field <code>repeated .Ydb.Topic.UpdateOffsetsInTransactionRequest.TopicOffsets topics = 3;</code>
     * @param array<\Ydb\Topic\UpdateOffsetsInTransactionRequest\TopicOffsets>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTopics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ydb\Topic\UpdateOffsetsInTransactionRequest\TopicOffsets::class);
        $this->topics = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string consumer = 4;</code>
     * @return string
     */
    public function getConsumer()
    {
        return $this->consumer;
    }

    /**
     * Generated from protobuf field <code>string consumer = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setConsumer($var)
    {
        GPBUtil::checkString($var, True);
        $this->consumer = $var;

        return $this;
    }

}

