<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_operation.proto

namespace Ydb\Operations;

if (false) {
    /**
     * This class is deprecated. Use Ydb\Operations\OperationParams\OperationMode instead.
     * @deprecated
     */
    class OperationParams_OperationMode {}
}
class_exists(OperationParams\OperationMode::class);
@trigger_error('Ydb\Operations\OperationParams_OperationMode is deprecated and will be removed in the next major release. Use Ydb\Operations\OperationParams\OperationMode instead', E_USER_DEPRECATED);

