<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_table.proto

namespace Ydb\Table;

if (false) {
    /**
     * This class is deprecated. Use Ydb\Table\ColumnFamilyPolicy\Compression instead.
     * @deprecated
     */
    class ColumnFamilyPolicy_Compression {}
}
class_exists(ColumnFamilyPolicy\Compression::class);
@trigger_error('Ydb\Table\ColumnFamilyPolicy_Compression is deprecated and will be removed in the next major release. Use Ydb\Table\ColumnFamilyPolicy\Compression instead', E_USER_DEPRECATED);

