<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_table.proto

namespace Ydb\Table;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.Table.CompactionPolicy</code>
 */
class CompactionPolicy extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string preset_name = 1;</code>
     */
    protected $preset_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $preset_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTable::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string preset_name = 1;</code>
     * @return string
     */
    public function getPresetName()
    {
        return $this->preset_name;
    }

    /**
     * Generated from protobuf field <code>string preset_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPresetName($var)
    {
        GPBUtil::checkString($var, True);
        $this->preset_name = $var;

        return $this;
    }

}

