<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_table.proto

namespace Ydb\Table;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * One QueryResult can contain multiple tables
 *
 * Generated from protobuf message <code>Ydb.Table.ExecuteQueryResult</code>
 */
class ExecuteQueryResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Result rets (for each table)
     *
     * Generated from protobuf field <code>repeated .Ydb.ResultSet result_sets = 1;</code>
     */
    private $result_sets;
    /**
     * Transaction metadata
     *
     * Generated from protobuf field <code>.Ydb.Table.TransactionMeta tx_meta = 2;</code>
     */
    protected $tx_meta = null;
    /**
     * Query metadata
     *
     * Generated from protobuf field <code>.Ydb.Table.QueryMeta query_meta = 3;</code>
     */
    protected $query_meta = null;
    /**
     * Query execution statistics
     *
     * Generated from protobuf field <code>.Ydb.TableStats.QueryStats query_stats = 4;</code>
     */
    protected $query_stats = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Ydb\ResultSet>|\Google\Protobuf\Internal\RepeatedField $result_sets
     *           Result rets (for each table)
     *     @type \Ydb\Table\TransactionMeta $tx_meta
     *           Transaction metadata
     *     @type \Ydb\Table\QueryMeta $query_meta
     *           Query metadata
     *     @type \Ydb\TableStats\QueryStats $query_stats
     *           Query execution statistics
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTable::initOnce();
        parent::__construct($data);
    }

    /**
     * Result rets (for each table)
     *
     * Generated from protobuf field <code>repeated .Ydb.ResultSet result_sets = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResultSets()
    {
        return $this->result_sets;
    }

    /**
     * Result rets (for each table)
     *
     * Generated from protobuf field <code>repeated .Ydb.ResultSet result_sets = 1;</code>
     * @param array<\Ydb\ResultSet>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResultSets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ydb\ResultSet::class);
        $this->result_sets = $arr;

        return $this;
    }

    /**
     * Transaction metadata
     *
     * Generated from protobuf field <code>.Ydb.Table.TransactionMeta tx_meta = 2;</code>
     * @return \Ydb\Table\TransactionMeta|null
     */
    public function getTxMeta()
    {
        return $this->tx_meta;
    }

    public function hasTxMeta()
    {
        return isset($this->tx_meta);
    }

    public function clearTxMeta()
    {
        unset($this->tx_meta);
    }

    /**
     * Transaction metadata
     *
     * Generated from protobuf field <code>.Ydb.Table.TransactionMeta tx_meta = 2;</code>
     * @param \Ydb\Table\TransactionMeta $var
     * @return $this
     */
    public function setTxMeta($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Table\TransactionMeta::class);
        $this->tx_meta = $var;

        return $this;
    }

    /**
     * Query metadata
     *
     * Generated from protobuf field <code>.Ydb.Table.QueryMeta query_meta = 3;</code>
     * @return \Ydb\Table\QueryMeta|null
     */
    public function getQueryMeta()
    {
        return $this->query_meta;
    }

    public function hasQueryMeta()
    {
        return isset($this->query_meta);
    }

    public function clearQueryMeta()
    {
        unset($this->query_meta);
    }

    /**
     * Query metadata
     *
     * Generated from protobuf field <code>.Ydb.Table.QueryMeta query_meta = 3;</code>
     * @param \Ydb\Table\QueryMeta $var
     * @return $this
     */
    public function setQueryMeta($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Table\QueryMeta::class);
        $this->query_meta = $var;

        return $this;
    }

    /**
     * Query execution statistics
     *
     * Generated from protobuf field <code>.Ydb.TableStats.QueryStats query_stats = 4;</code>
     * @return \Ydb\TableStats\QueryStats|null
     */
    public function getQueryStats()
    {
        return $this->query_stats;
    }

    public function hasQueryStats()
    {
        return isset($this->query_stats);
    }

    public function clearQueryStats()
    {
        unset($this->query_stats);
    }

    /**
     * Query execution statistics
     *
     * Generated from protobuf field <code>.Ydb.TableStats.QueryStats query_stats = 4;</code>
     * @param \Ydb\TableStats\QueryStats $var
     * @return $this
     */
    public function setQueryStats($var)
    {
        GPBUtil::checkMessage($var, \Ydb\TableStats\QueryStats::class);
        $this->query_stats = $var;

        return $this;
    }

}

