<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_table.proto

namespace Ydb\Table;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request to read table (without SQL)
 *
 * Generated from protobuf message <code>Ydb.Table.ReadTableRequest</code>
 */
class ReadTableRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Session identifier
     *
     * Generated from protobuf field <code>string session_id = 1;</code>
     */
    protected $session_id = '';
    /**
     * Path to table to read
     *
     * Generated from protobuf field <code>string path = 2;</code>
     */
    protected $path = '';
    /**
     * Primary key range to read
     *
     * Generated from protobuf field <code>.Ydb.Table.KeyRange key_range = 3;</code>
     */
    protected $key_range = null;
    /**
     * Output columns
     *
     * Generated from protobuf field <code>repeated string columns = 4;</code>
     */
    private $columns;
    /**
     * Require ordered reading
     *
     * Generated from protobuf field <code>bool ordered = 5;</code>
     */
    protected $ordered = false;
    /**
     * Limits row count to read
     *
     * Generated from protobuf field <code>uint64 row_limit = 6;</code>
     */
    protected $row_limit = 0;
    /**
     * Use a server-side snapshot
     *
     * Generated from protobuf field <code>.Ydb.FeatureFlag.Status use_snapshot = 7;</code>
     */
    protected $use_snapshot = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $session_id
     *           Session identifier
     *     @type string $path
     *           Path to table to read
     *     @type \Ydb\Table\KeyRange $key_range
     *           Primary key range to read
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $columns
     *           Output columns
     *     @type bool $ordered
     *           Require ordered reading
     *     @type int|string $row_limit
     *           Limits row count to read
     *     @type int $use_snapshot
     *           Use a server-side snapshot
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTable::initOnce();
        parent::__construct($data);
    }

    /**
     * Session identifier
     *
     * Generated from protobuf field <code>string session_id = 1;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * Session identifier
     *
     * Generated from protobuf field <code>string session_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

    /**
     * Path to table to read
     *
     * Generated from protobuf field <code>string path = 2;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Path to table to read
     *
     * Generated from protobuf field <code>string path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Primary key range to read
     *
     * Generated from protobuf field <code>.Ydb.Table.KeyRange key_range = 3;</code>
     * @return \Ydb\Table\KeyRange|null
     */
    public function getKeyRange()
    {
        return $this->key_range;
    }

    public function hasKeyRange()
    {
        return isset($this->key_range);
    }

    public function clearKeyRange()
    {
        unset($this->key_range);
    }

    /**
     * Primary key range to read
     *
     * Generated from protobuf field <code>.Ydb.Table.KeyRange key_range = 3;</code>
     * @param \Ydb\Table\KeyRange $var
     * @return $this
     */
    public function setKeyRange($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Table\KeyRange::class);
        $this->key_range = $var;

        return $this;
    }

    /**
     * Output columns
     *
     * Generated from protobuf field <code>repeated string columns = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getColumns()
    {
        return $this->columns;
    }

    /**
     * Output columns
     *
     * Generated from protobuf field <code>repeated string columns = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setColumns($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->columns = $arr;

        return $this;
    }

    /**
     * Require ordered reading
     *
     * Generated from protobuf field <code>bool ordered = 5;</code>
     * @return bool
     */
    public function getOrdered()
    {
        return $this->ordered;
    }

    /**
     * Require ordered reading
     *
     * Generated from protobuf field <code>bool ordered = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setOrdered($var)
    {
        GPBUtil::checkBool($var);
        $this->ordered = $var;

        return $this;
    }

    /**
     * Limits row count to read
     *
     * Generated from protobuf field <code>uint64 row_limit = 6;</code>
     * @return int|string
     */
    public function getRowLimit()
    {
        return $this->row_limit;
    }

    /**
     * Limits row count to read
     *
     * Generated from protobuf field <code>uint64 row_limit = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRowLimit($var)
    {
        GPBUtil::checkUint64($var);
        $this->row_limit = $var;

        return $this;
    }

    /**
     * Use a server-side snapshot
     *
     * Generated from protobuf field <code>.Ydb.FeatureFlag.Status use_snapshot = 7;</code>
     * @return int
     */
    public function getUseSnapshot()
    {
        return $this->use_snapshot;
    }

    /**
     * Use a server-side snapshot
     *
     * Generated from protobuf field <code>.Ydb.FeatureFlag.Status use_snapshot = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setUseSnapshot($var)
    {
        GPBUtil::checkEnum($var, \Ydb\FeatureFlag\Status::class);
        $this->use_snapshot = $var;

        return $this;
    }

}

