<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_table.proto

namespace Ydb\Table;

use UnexpectedValueException;

/**
 * Protobuf type <code>Ydb.Table.StoreType</code>
 */
class StoreType
{
    /**
     * Generated from protobuf enum <code>STORE_TYPE_UNSPECIFIED = 0;</code>
     */
    const STORE_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>STORE_TYPE_ROW = 1;</code>
     */
    const STORE_TYPE_ROW = 1;
    /**
     * Generated from protobuf enum <code>STORE_TYPE_COLUMN = 2;</code>
     */
    const STORE_TYPE_COLUMN = 2;

    private static $valueToName = [
        self::STORE_TYPE_UNSPECIFIED => 'STORE_TYPE_UNSPECIFIED',
        self::STORE_TYPE_ROW => 'STORE_TYPE_ROW',
        self::STORE_TYPE_COLUMN => 'STORE_TYPE_COLUMN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

