<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_table.proto

namespace Ydb\Table;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Represent secondary index
 *
 * Generated from protobuf message <code>Ydb.Table.TableIndex</code>
 */
class TableIndex extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of index
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * list of columns
     *
     * Generated from protobuf field <code>repeated string index_columns = 2;</code>
     */
    private $index_columns;
    /**
     * list of columns content to be copied in to index table
     *
     * Generated from protobuf field <code>repeated string data_columns = 4;</code>
     */
    private $data_columns;
    protected $type;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Name of index
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $index_columns
     *           list of columns
     *     @type \Ydb\Table\GlobalIndex $global_index
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $data_columns
     *           list of columns content to be copied in to index table
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kikimr\PBPublic\Api\Protos\YdbTable::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of index
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name of index
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * list of columns
     *
     * Generated from protobuf field <code>repeated string index_columns = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndexColumns()
    {
        return $this->index_columns;
    }

    /**
     * list of columns
     *
     * Generated from protobuf field <code>repeated string index_columns = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndexColumns($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->index_columns = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Table.GlobalIndex global_index = 3;</code>
     * @return \Ydb\Table\GlobalIndex
     */
    public function getGlobalIndex()
    {
        return $this->readOneof(3);
    }

    public function hasGlobalIndex()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Table.GlobalIndex global_index = 3;</code>
     * @param \Ydb\Table\GlobalIndex $var
     * @return $this
     */
    public function setGlobalIndex($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Table\GlobalIndex::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * list of columns content to be copied in to index table
     *
     * Generated from protobuf field <code>repeated string data_columns = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDataColumns()
    {
        return $this->data_columns;
    }

    /**
     * list of columns content to be copied in to index table
     *
     * Generated from protobuf field <code>repeated string data_columns = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDataColumns($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->data_columns = $arr;

        return $this;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->whichOneof("type");
    }

}

