<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_topic.proto

namespace Ydb\Topic\StreamReadMessage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Signal from server that client has finished reading the partition and all messages have been read.
 * Once a partition has been finished no further messages will ever arrive to that partition.
 * This command is a hint to the client to commit offsets, after which the child partitions will be balanced independently in different reading sessions.
 * Unlike StopPartitionSessionRequest, the client does not have to close the reading session.
 * Client should not send a response to the command.
 *
 * Generated from protobuf message <code>Ydb.Topic.StreamReadMessage.EndPartitionSession</code>
 */
class EndPartitionSession extends \Google\Protobuf\Internal\Message
{
    /**
     * Partition session identifier.
     *
     * Generated from protobuf field <code>int64 partition_session_id = 1;</code>
     */
    protected $partition_session_id = 0;
    /**
     * Ids of partitions which were merged with the ended partition.
     *
     * Generated from protobuf field <code>repeated int64 adjacent_partition_ids = 2;</code>
     */
    private $adjacent_partition_ids;
    /**
     * Ids of partitions which was formed when the ended partition was split or merged.
     *
     * Generated from protobuf field <code>repeated int64 child_partition_ids = 3;</code>
     */
    private $child_partition_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $partition_session_id
     *           Partition session identifier.
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $adjacent_partition_ids
     *           Ids of partitions which were merged with the ended partition.
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $child_partition_ids
     *           Ids of partitions which was formed when the ended partition was split or merged.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTopic::initOnce();
        parent::__construct($data);
    }

    /**
     * Partition session identifier.
     *
     * Generated from protobuf field <code>int64 partition_session_id = 1;</code>
     * @return int|string
     */
    public function getPartitionSessionId()
    {
        return $this->partition_session_id;
    }

    /**
     * Partition session identifier.
     *
     * Generated from protobuf field <code>int64 partition_session_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPartitionSessionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->partition_session_id = $var;

        return $this;
    }

    /**
     * Ids of partitions which were merged with the ended partition.
     *
     * Generated from protobuf field <code>repeated int64 adjacent_partition_ids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAdjacentPartitionIds()
    {
        return $this->adjacent_partition_ids;
    }

    /**
     * Ids of partitions which were merged with the ended partition.
     *
     * Generated from protobuf field <code>repeated int64 adjacent_partition_ids = 2;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAdjacentPartitionIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->adjacent_partition_ids = $arr;

        return $this;
    }

    /**
     * Ids of partitions which was formed when the ended partition was split or merged.
     *
     * Generated from protobuf field <code>repeated int64 child_partition_ids = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChildPartitionIds()
    {
        return $this->child_partition_ids;
    }

    /**
     * Ids of partitions which was formed when the ended partition was split or merged.
     *
     * Generated from protobuf field <code>repeated int64 child_partition_ids = 3;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChildPartitionIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->child_partition_ids = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(EndPartitionSession::class, \Ydb\Topic\StreamReadMessage_EndPartitionSession::class);

