<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ydb_topic.proto

namespace Ydb\Topic\StreamReadMessage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Handshake request.
 *
 * Generated from protobuf message <code>Ydb.Topic.StreamReadMessage.InitRequest</code>
 */
class InitRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Message that describes topic to read.
     * Topics that will be read by this session.
     *
     * Generated from protobuf field <code>repeated .Ydb.Topic.StreamReadMessage.InitRequest.TopicReadSettings topics_read_settings = 1;</code>
     */
    private $topics_read_settings;
    /**
     * Path of consumer that is used for reading by this session.
     *
     * Generated from protobuf field <code>string consumer = 2;</code>
     */
    protected $consumer = '';
    /**
     * Optional name. Will be shown in debug stat.
     *
     * Generated from protobuf field <code>string reader_name = 3;</code>
     */
    protected $reader_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Ydb\Topic\StreamReadMessage\InitRequest\TopicReadSettings>|\Google\Protobuf\Internal\RepeatedField $topics_read_settings
     *           Message that describes topic to read.
     *           Topics that will be read by this session.
     *     @type string $consumer
     *           Path of consumer that is used for reading by this session.
     *     @type string $reader_name
     *           Optional name. Will be shown in debug stat.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\YdbTopic::initOnce();
        parent::__construct($data);
    }

    /**
     * Message that describes topic to read.
     * Topics that will be read by this session.
     *
     * Generated from protobuf field <code>repeated .Ydb.Topic.StreamReadMessage.InitRequest.TopicReadSettings topics_read_settings = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTopicsReadSettings()
    {
        return $this->topics_read_settings;
    }

    /**
     * Message that describes topic to read.
     * Topics that will be read by this session.
     *
     * Generated from protobuf field <code>repeated .Ydb.Topic.StreamReadMessage.InitRequest.TopicReadSettings topics_read_settings = 1;</code>
     * @param array<\Ydb\Topic\StreamReadMessage\InitRequest\TopicReadSettings>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTopicsReadSettings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ydb\Topic\StreamReadMessage\InitRequest\TopicReadSettings::class);
        $this->topics_read_settings = $arr;

        return $this;
    }

    /**
     * Path of consumer that is used for reading by this session.
     *
     * Generated from protobuf field <code>string consumer = 2;</code>
     * @return string
     */
    public function getConsumer()
    {
        return $this->consumer;
    }

    /**
     * Path of consumer that is used for reading by this session.
     *
     * Generated from protobuf field <code>string consumer = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setConsumer($var)
    {
        GPBUtil::checkString($var, True);
        $this->consumer = $var;

        return $this;
    }

    /**
     * Optional name. Will be shown in debug stat.
     *
     * Generated from protobuf field <code>string reader_name = 3;</code>
     * @return string
     */
    public function getReaderName()
    {
        return $this->reader_name;
    }

    /**
     * Optional name. Will be shown in debug stat.
     *
     * Generated from protobuf field <code>string reader_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setReaderName($var)
    {
        GPBUtil::checkString($var, True);
        $this->reader_name = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(InitRequest::class, \Ydb\Topic\StreamReadMessage_InitRequest::class);

