<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_yql_internal.proto

namespace Ydb\YqlInternal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.YqlInternal.ExecDataQueryAstResult</code>
 */
class ExecDataQueryAstResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Ydb.ResultSet result_sets = 1;</code>
     */
    private $result_sets;
    /**
     * Generated from protobuf field <code>string query_ast = 2;</code>
     */
    protected $query_ast = '';
    /**
     * Generated from protobuf field <code>string query_plan = 3;</code>
     */
    protected $query_plan = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ydb\ResultSet[]|\Google\Protobuf\Internal\RepeatedField $result_sets
     *     @type string $query_ast
     *     @type string $query_plan
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kikimr\PBPublic\Api\Protos\YdbYqlInternal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.ResultSet result_sets = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResultSets()
    {
        return $this->result_sets;
    }

    /**
     * Generated from protobuf field <code>repeated .Ydb.ResultSet result_sets = 1;</code>
     * @param \Ydb\ResultSet[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResultSets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ydb\ResultSet::class);
        $this->result_sets = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string query_ast = 2;</code>
     * @return string
     */
    public function getQueryAst()
    {
        return $this->query_ast;
    }

    /**
     * Generated from protobuf field <code>string query_ast = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setQueryAst($var)
    {
        GPBUtil::checkString($var, True);
        $this->query_ast = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string query_plan = 3;</code>
     * @return string
     */
    public function getQueryPlan()
    {
        return $this->query_plan;
    }

    /**
     * Generated from protobuf field <code>string query_plan = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setQueryPlan($var)
    {
        GPBUtil::checkString($var, True);
        $this->query_plan = $var;

        return $this;
    }

}

