<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_yql_internal.proto

namespace Ydb\YqlInternal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.YqlInternal.ExecDataQueryAstRequest</code>
 */
class ExecDataQueryAstRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     */
    protected $operation_params = null;
    /**
     * Generated from protobuf field <code>string cluster_name = 2;</code>
     */
    protected $cluster_name = '';
    /**
     * Generated from protobuf field <code>string query_ast = 3;</code>
     */
    protected $query_ast = '';
    /**
     * Generated from protobuf field <code>map<string, .Ydb.TypedValue> parameters = 4;</code>
     */
    private $parameters;
    /**
     * Generated from protobuf field <code>.Ydb.Table.TransactionSettings tx_settings = 5;</code>
     */
    protected $tx_settings = null;
    /**
     * Generated from protobuf field <code>.Ydb.YqlInternal.ExecQuerySettings settings = 6;</code>
     */
    protected $settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ydb\Operations\OperationParams $operation_params
     *     @type string $cluster_name
     *     @type string $query_ast
     *     @type array|\Google\Protobuf\Internal\MapField $parameters
     *     @type \Ydb\Table\TransactionSettings $tx_settings
     *     @type \Ydb\YqlInternal\ExecQuerySettings $settings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kikimr\PBPublic\Api\Protos\YdbYqlInternal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     * @return \Ydb\Operations\OperationParams
     */
    public function getOperationParams()
    {
        return isset($this->operation_params) ? $this->operation_params : null;
    }

    public function hasOperationParams()
    {
        return isset($this->operation_params);
    }

    public function clearOperationParams()
    {
        unset($this->operation_params);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
     * @param \Ydb\Operations\OperationParams $var
     * @return $this
     */
    public function setOperationParams($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Operations\OperationParams::class);
        $this->operation_params = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cluster_name = 2;</code>
     * @return string
     */
    public function getClusterName()
    {
        return $this->cluster_name;
    }

    /**
     * Generated from protobuf field <code>string cluster_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClusterName($var)
    {
        GPBUtil::checkString($var, True);
        $this->cluster_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string query_ast = 3;</code>
     * @return string
     */
    public function getQueryAst()
    {
        return $this->query_ast;
    }

    /**
     * Generated from protobuf field <code>string query_ast = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setQueryAst($var)
    {
        GPBUtil::checkString($var, True);
        $this->query_ast = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .Ydb.TypedValue> parameters = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    /**
     * Generated from protobuf field <code>map<string, .Ydb.TypedValue> parameters = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setParameters($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ydb\TypedValue::class);
        $this->parameters = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.Table.TransactionSettings tx_settings = 5;</code>
     * @return \Ydb\Table\TransactionSettings
     */
    public function getTxSettings()
    {
        return isset($this->tx_settings) ? $this->tx_settings : null;
    }

    public function hasTxSettings()
    {
        return isset($this->tx_settings);
    }

    public function clearTxSettings()
    {
        unset($this->tx_settings);
    }

    /**
     * Generated from protobuf field <code>.Ydb.Table.TransactionSettings tx_settings = 5;</code>
     * @param \Ydb\Table\TransactionSettings $var
     * @return $this
     */
    public function setTxSettings($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Table\TransactionSettings::class);
        $this->tx_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ydb.YqlInternal.ExecQuerySettings settings = 6;</code>
     * @return \Ydb\YqlInternal\ExecQuerySettings
     */
    public function getSettings()
    {
        return isset($this->settings) ? $this->settings : null;
    }

    public function hasSettings()
    {
        return isset($this->settings);
    }

    public function clearSettings()
    {
        unset($this->settings);
    }

    /**
     * Generated from protobuf field <code>.Ydb.YqlInternal.ExecQuerySettings settings = 6;</code>
     * @param \Ydb\YqlInternal\ExecQuerySettings $var
     * @return $this
     */
    public function setSettings($var)
    {
        GPBUtil::checkMessage($var, \Ydb\YqlInternal\ExecQuerySettings::class);
        $this->settings = $var;

        return $this;
    }

}

