name: linter

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  GRPC_VERSION: '1.51.1'
  CACHE_VERSION: 'v1'

jobs:
  linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '7.2' ]

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: ./.github/actions/setup-php-grpc
        with:
          php-version: ${{ matrix.php-versions }}
          grpc-version: ${{ env.GRPC_VERSION }}
          cache-version: ${{ env.CACHE_VERSION }}

      - run: composer validate --strict
        name: Validate composer.json and composer.lock

      - uses: actions/cache@v3
        name: Cache Composer packages
        id: composer-cache

        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: ./vendor/bin/phplint \
          ./ --exclude=vendor
