name: tests

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  GRPC_VERSION: '1.51.1'
  CACHE_VERSION: 'v1'

jobs:
  prepare-grpc:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '7.2', '7.4', '8.0', '8.2' ]
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: shivammathur/setup-php@v2
        name: Setup PHP
        with:
          php-version: ${{ matrix.php-versions }}
          tools: pecl

      - name: Resolve extension dir
        run: echo "EXT_DIR=$(php-config --extension-dir)" >> "$GITHUB_ENV"

      - name: Cache PHP grpc extension
        id: grpc-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.EXT_DIR }}/grpc.so
          key: php-grpc-${{ matrix.php-versions }}-${{ runner.os }}-grpc${{ env.GRPC_VERSION }}-${{ env.CACHE_VERSION }}

      - uses: eWaterCycle/setup-grpc@v5
        if: steps.grpc-cache.outputs.cache-hit != 'true'
        name: Setup gRPC
        with:
          grpc-version: ${{ env.GRPC_VERSION }}

      - name: Build grpc PHP extension
        if: steps.grpc-cache.outputs.cache-hit != 'true'
        run: sudo pecl install grpc

  tests:
    needs: prepare-grpc
    services:
      ydb:
        image: cr.yandex/yc/yandex-docker-local-ydb:${{ matrix.ydb-versions }}
        ports:
          - 2135:2135
          - 2136:2136
          - 8765:8765
        volumes:
          - /tmp/ydb_certs:/ydb_certs
        env:
          YDB_USE_IN_MEMORY_PDISKS: true
        options: '-h localhost'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '7.2', '7.4', '8.0', '8.2' ]
        ydb-versions: ['stable-22-5', 'trunk', '23.3', '23.2', '23.1']
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: shivammathur/setup-php@v2
        name: Setup PHP
        id: php
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Resolve extension dir
        run: echo "EXT_DIR=$(php-config --extension-dir)" >> "$GITHUB_ENV"

      - name: Restore PHP grpc extension
        id: grpc-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.EXT_DIR }}/grpc.so
          key: php-grpc-${{ matrix.php-versions }}-${{ runner.os }}-grpc${{ env.GRPC_VERSION }}-${{ env.CACHE_VERSION }}

      - name: Enable grpc extension
        run: |
          INI_DIR=$(php -r 'echo PHP_CONFIG_FILE_SCAN_DIR;')
          echo "extension=grpc.so" | sudo tee "$INI_DIR/20-grpc.ini"
          php -m | grep -i grpc

      - run: composer validate --strict
        name: Validate composer.json and composer.lock

      - uses: actions/cache@v3
        name: Cache Composer packages
        id: composer-cache

        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create YDB User
        run: docker exec $(docker ps --latest --quiet) /ydb -e grpc://localhost:2136 -d /local scripting yql -s "CREATE USER testuser PASSWORD 'testpassword'"

      - name: Run tests
        run: ./vendor/bin/phpunit \
          --coverage-text \
          --whitelist src \
          --testdox \
          tests
